#include "pg_parser_os_incl.h"
#include "pg_parser_app_incl.h"

/**
 * @brief          Correspondence between error codes and error messages
 */
typedef struct PG_PARSER_ERRNO_2_MSG
{
    int32_t m_errno;    /*!< Error code value */
    char*   m_errormsg; /*!< Error message */
} pg_parser_errno_2_msg;

/**
 * @brief          All error codes and their error messages
 */
static pg_parser_errno_2_msg m_errno_2_msg[] = {
    {ERRNO_SUCCESS,                                                         "Success"                                                               },
    {ERRNO_PG_PARSER_PRE_USELESS,                                           "Missing pre-parse function"                                            },
    {ERRNO_PG_PARSER_PRE_MEMERR_BEGIN,                                      "Memory error code start flag"                                          },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_00,                            "Invalid record pre-parse memory allocation failed"                     },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_01,                            "heap_insert record pre-parse memory allocation failed"                 },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_02,                            "heap_update record pre-parse memory allocation failed"                 },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_03,                            "heap_hot_update record pre-parse memory allocation failed"             },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_04,                            "heap_delete record pre-parse memory allocation failed"                 },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_05,                            "heap2_multi_insert record pre-parse memory allocation failed"          },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_06,                            "xact_commit record pre-parse memory allocation failed"                 },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_07,                            "xact_abort record pre-parse memory allocation failed"                  },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_08,                            "xact_switch record pre-parse memory allocation failed"                 },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_09,                            "xlog_checkpoint_online record pre-parse memory allocation failed"      },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_0A,                            "xlog_checkpoint_shutdown record pre-parse memory allocation failed"    },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_DECODESTATE,                          "record state memory allocation failed"                                 },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_BLOCK,                                "Memory allocation failed for full page write data when decoding record"},
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_MAINDATA,                             "Memory allocation failed for maindata when decoding record"            },
    {ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_IMAGE_FPW,                            "pg_parser_check_fpw memory allocation for full page write failed"      },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_00,                                 "Memory allocation failed during parsing, location: 00"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_01,                                 "Memory allocation failed during parsing, location: 01"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_02,                                 "Memory allocation failed during parsing, location: 02"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_03,                                 "Memory allocation failed during parsing, location: 03"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_04,                                 "Memory allocation failed during parsing, location: 04"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_05,                                 "Memory allocation failed during parsing, location: 05"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_06,                                 "Memory allocation failed during parsing, location: 06"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_07,                                 "Memory allocation failed during parsing, location: 07"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_08,                                 "Memory allocation failed during parsing, location: 08"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_09,                                 "Memory allocation failed during parsing, location: 09"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0A,                                 "Memory allocation failed during parsing, location: 0A"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0B,                                 "Memory allocation failed during parsing, location: 0B"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0C,                                 "Memory allocation failed during parsing, location: 0C"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0D,                                 "Memory allocation failed during parsing, location: 0D"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0E,                                 "Memory allocation failed during parsing, location: 0E"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0F,                                 "Memory allocation failed during parsing, location: 0F"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_10,                                 "Memory allocation failed during parsing, location: 10"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_11,                                 "Memory allocation failed during parsing, location: 11"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_12,                                 "Memory allocation failed during parsing, location: 12"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_13,                                 "Memory allocation failed during parsing, location: 13"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_14,                                 "Memory allocation failed during parsing, location: 14"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_15,                                 "Memory allocation failed during parsing, location: 15"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_16,                                 "Memory allocation failed during parsing, location: 16"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_17,                                 "Memory allocation failed during parsing, location: 17"                 },
    {ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_18,                                 "Memory allocation failed during parsing, location: 18"                 },
    {ERRNO_PG_PARSER_EXTERNAL_MEMERR_ALLOC_00,
     "Memory allocation failed during out-of-line storage data parsing, location: 00"                                                               },
    {ERRNO_PG_PARSER_EXTERNAL_MEMERR_ALLOC_01,
     "Memory allocation failed during out-of-line storage data parsing, location: 01"                                                               },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_00,                                   "Memory allocation failed during DDL parsing, location: 00"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_01,                                   "Memory allocation failed during DDL parsing, location: 01"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_02,                                   "Memory allocation failed during DDL parsing, location: 02"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_03,                                   "Memory allocation failed during DDL parsing, location: 03"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_04,                                   "Memory allocation failed during DDL parsing, location: 04"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_05,                                   "Memory allocation failed during DDL parsing, location: 05"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_06,                                   "Memory allocation failed during DDL parsing, location: 06"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_07,                                   "Memory allocation failed during DDL parsing, location: 07"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_08,                                   "Memory allocation failed during DDL parsing, location: 08"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_09,                                   "Memory allocation failed during DDL parsing, location: 09"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0A,                                   "Memory allocation failed during DDL parsing, location: 0A"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0B,                                   "Memory allocation failed during DDL parsing, location: 0B"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0C,                                   "Memory allocation failed during DDL parsing, location: 0C"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0D,                                   "Memory allocation failed during DDL parsing, location: 0D"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0E,                                   "Memory allocation failed during DDL parsing, location: 0E"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0F,                                   "Memory allocation failed during DDL parsing, location: 0F"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_10,                                   "Memory allocation failed during DDL parsing, location: 10"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_11,                                   "Memory allocation failed during DDL parsing, location: 11"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_12,                                   "Memory allocation failed during DDL parsing, location: 12"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_13,                                   "Memory allocation failed during DDL parsing, location: 13"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_14,                                   "Memory allocation failed during DDL parsing, location: 14"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_15,                                   "Memory allocation failed during DDL parsing, location: 15"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_16,                                   "Memory allocation failed during DDL parsing, location: 16"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_17,                                   "Memory allocation failed during DDL parsing, location: 17"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_18,                                   "Memory allocation failed during DDL parsing, location: 18"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_19,                                   "Memory allocation failed during DDL parsing, location: 19"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1A,                                   "Memory allocation failed during DDL parsing, location: 1A"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1B,                                   "Memory allocation failed during DDL parsing, location: 1B"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1C,                                   "Memory allocation failed during DDL parsing, location: 1C"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1D,                                   "Memory allocation failed during DDL parsing, location: 1D"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1E,                                   "Memory allocation failed during DDL parsing, location: 1E"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1F,                                   "Memory allocation failed during DDL parsing, location: 1F"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_20,                                   "Memory allocation failed during DDL parsing, location: 20"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_21,                                   "Memory allocation failed during DDL parsing, location: 21"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_22,                                   "Memory allocation failed during DDL parsing, location: 22"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_23,                                   "Memory allocation failed during DDL parsing, location: 23"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_24,                                   "Memory allocation failed during DDL parsing, location: 24"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_25,                                   "Memory allocation failed during DDL parsing, location: 25"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_26,                                   "Memory allocation failed during DDL parsing, location: 26"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_27,                                   "Memory allocation failed during DDL parsing, location: 27"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_28,                                   "Memory allocation failed during DDL parsing, location: 28"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_29,                                   "Memory allocation failed during DDL parsing, location: 29"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2A,                                   "Memory allocation failed during DDL parsing, location: 2A"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2B,                                   "Memory allocation failed during DDL parsing, location: 2B"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2C,                                   "Memory allocation failed during DDL parsing, location: 2C"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2D,                                   "Memory allocation failed during DDL parsing, location: 2D"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2E,                                   "Memory allocation failed during DDL parsing, location: 2E"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2F,                                   "Memory allocation failed during DDL parsing, location: 2F"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_30,                                   "Memory allocation failed during DDL parsing, location: 30"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_31,                                   "Memory allocation failed during DDL parsing, location: 31"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_32,                                   "Memory allocation failed during DDL parsing, location: 32"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_33,                                   "Memory allocation failed during DDL parsing, location: 33"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_34,                                   "Memory allocation failed during DDL parsing, location: 34"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_35,                                   "Memory allocation failed during DDL parsing, location: 35"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_36,                                   "Memory allocation failed during DDL parsing, location: 36"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_37,                                   "Memory allocation failed during DDL parsing, location: 37"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_38,                                   "Memory allocation failed during DDL parsing, location: 38"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_39,                                   "Memory allocation failed during DDL parsing, location: 39"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3A,                                   "Memory allocation failed during DDL parsing, location: 3A"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3B,                                   "Memory allocation failed during DDL parsing, location: 3B"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3C,                                   "Memory allocation failed during DDL parsing, location: 3C"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3D,                                   "Memory allocation failed during DDL parsing, location: 3D"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3E,                                   "Memory allocation failed during DDL parsing, location: 3E"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3F,                                   "Memory allocation failed during DDL parsing, location: 3F"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_40,                                   "Memory allocation failed during DDL parsing, location: 40"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_41,                                   "Memory allocation failed during DDL parsing, location: 41"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_42,                                   "Memory allocation failed during DDL parsing, location: 42"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_43,                                   "Memory allocation failed during DDL parsing, location: 43"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_44,                                   "Memory allocation failed during DDL parsing, location: 44"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_45,                                   "Memory allocation failed during DDL parsing, location: 45"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_46,                                   "Memory allocation failed during DDL parsing, location: 46"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_47,                                   "Memory allocation failed during DDL parsing, location: 47"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_48,                                   "Memory allocation failed during DDL parsing, location: 48"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_49,                                   "Memory allocation failed during DDL parsing, location: 49"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4A,                                   "Memory allocation failed during DDL parsing, location: 4A"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4B,                                   "Memory allocation failed during DDL parsing, location: 4B"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4C,                                   "Memory allocation failed during DDL parsing, location: 4C"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4D,                                   "Memory allocation failed during DDL parsing, location: 4D"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4E,                                   "Memory allocation failed during DDL parsing, location: 4E"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4F,                                   "Memory allocation failed during DDL parsing, location: 4F"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_50,                                   "Memory allocation failed during DDL parsing, location: 50"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_51,                                   "Memory allocation failed during DDL parsing, location: 51"             },
    {ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_52,                                   "Memory allocation failed during DDL parsing, location: 52"             },
    {ERRNO_PG_PARSER_PRE_FUNCERR_PRE_CHECK,                                 "Invalid input parameter detected during pre-parsing"                   },
    {ERRNO_PG_PARSER_PRE_FUNCERR_PRE_DECODE,                                "RECORD decoding failed during pre-parsing"                             },
    {ERRNO_PG_PARSER_PRE_FUNCERR_PRE_PARAM_CHECK,                           "Invalid input parameter detected during pre-parsing"                   },
    {ERRNO_PG_PARSER_PRE_FUNCERR_HEAP_INSERT_CHECK,                         "Invalid input parameter detected during INSERT pre-parsing"            },
    {ERRNO_PG_PARSER_PRE_FUNCERR_HEAP2_MINSERT_CHECK,
     "Invalid input parameter detected during MULTI INSERT pre-parsing"                                                                             },
    {ERRNO_PG_PARSER_PRE_FUNCERR_HEAP_DELETE_CHECK,                         "Invalid input parameter detected during DELETE pre-parsing"            },
    {ERRNO_PG_PARSER_PRE_FUNCERR_HEAP_UPDATE_CHECK,                         "Invalid input parameter detected during UPDATE pre-parsing"            },
    {ERRNO_PG_PARSER_PRE_FUNCERR_HEAP_HUPDATE_CHECK,                        "Invalid input parameter detected during HOT UPDATE pre-parsing"        },
    {ERRNO_PG_PARSER_PRE_FUNCERR_XACT_COMMIT_CHECK,                         "Invalid input parameter detected during COMMIT pre-parsing"            },
    {ERRNO_PG_PARSER_PRE_FUNCERR_XACT_ABORT_CHECK,                          "Invalid input parameter detected during ABORT pre-parsing"             },
    {ERRNO_PG_PARSER_PRE_FUNCERR_XLOG_CKPS_CHECK,
     "Invalid input parameter detected during CHECKPOINT SHUTDOWN pre-parsing"                                                                      },
    {ERRNO_PG_PARSER_PRE_FUNCERR_XLOG_CKPO_CHECK,
     "Invalid input parameter detected during CHECKPOINT ONLINE pre-parsing"                                                                        },
    {ERRNO_PG_PARSER_PRE_FUNCERR_XLOG_SWITCH_CHECK,
     "Invalid input parameter detected during SWITCH RECORD pre-parsing"                                                                            },
    {ERRNO_PG_PARSER_DECODE_RECORD_BLOCKID_CHECK,                           "Error in block_id parsing result when parsing record"                  },
    {ERRNO_PG_PARSER_DECODE_RECORD_NODATA,                                  "Data flag set when parsing record, but no data in record"              },
    {ERRNO_PG_PARSER_DECODE_RECORD_DATASET,                                 "DATA flag not set when parsing record, but data exists"                },
    {ERRNO_PG_PARSER_DECODE_RECORD_HASHOLE,                                 "Hole flag not set when parsing record, but hole length > 0"            },
    {ERRNO_PG_PARSER_DECODE_RECORD_HASCOMPRESSED,
     "Compression flag set when parsing record, but length value is invalid"                                                                        },
    {ERRNO_PG_PARSER_DECODE_RECORD_COMPRESSED_LENGTH,                       "Compression or hole length invalid when parsing record"                },
    {ERRNO_PG_PARSER_DECODE_RECORD_NOSAMEREL,                               "Same rel flag set when parsing record, but no previous rel data"       },
    {ERRNO_PG_PARSER_DECODE_RECORD_INVALID_BLOCKID,                         "Blockid invalid when parsing record"                                   },
    {ERRNO_PG_PARSER_DECODE_RECORD_SHORT,                                   "Data length after record parsing does not match accumulated value"     },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_CHECK,                       "Invalid input parameter detected when parsing INSERT"                  },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MINSERT_CHECK,                     "Invalid input parameter detected when parsing MULTI INSERT"            },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_CHECK,                       "Invalid input parameter detected when parsing UPDATE"                  },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_CHECK,                       "Invalid input parameter detected when parsing DELETE"                  },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_TRANS_DECODE,                            "RECORD decoding failed during parsing"                                 },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_TBINFO,                      "Failed to get tbinfo when parsing INSERT"                              },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_GET_IMAGE,                   "Failed to parse full page write data when parsing INSERT"              },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_GET_TUPLE,                   "Failed to get tuple data when parsing INSERT"                          },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_GET_TEMP_TUPLE,              "Failed to build tuple when parsing INSERT"                             },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_GET_TUPLE2,                  "Failed to get tuple data when parsing INSERT"                          },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_GET_TEMP_TUPLE2,             "Failed to build tuple when parsing INSERT"                             },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_LOGICAL_NEWTUPLE_FLAG,
     "No tupleflag in logical mode when parsing INSERT"                                                                                             },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_LOGICAL_GET_TUPLE,
     "Failed to get tuple data in logical mode when parsing INSERT"                                                                                 },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_LOGICAL_GET_TEMPTUPLE,
     "Failed to build tuple in logical mode when parsing INSERT"                                                                                    },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_MAKE_DESC,                   "Failed to build DESC when parsing INSERT"                              },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_CONVERT_ATTR_TO_CHAR,        "Failed to parse column data when parsing INSERT"                       },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_TBINFO,               "Failed to get tbinfo when parsing MULTI INSERT"                        },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_GET_IMAGE,
     "Failed to parse full page write data when parsing MULTI INSERT"                                                                               },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_GET_TUPLE,            "Failed to get tuple data when parsing MULTI INSERT"                    },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_GET_TEMP_TUPLE,
     "Failed to build tuple when parsing MULTI INSERT"                                                                                              },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_LOGICAL_NEW_FLAG,
     "No tupleflag in logical mode when parsing MULTI INSERT"                                                                                       },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_LOGICAL_DATA,
     "Failed to get tuple data in logical mode when parsing MULTI INSERT"                                                                           },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_MAKE_DESC,            "Failed to build DESC when parsing MULTI INSERT"                        },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_CONVERT_ATTR_TO_CHAR,
     "Failed to parse column data when parsing MULTI INSERT"                                                                                        },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_TBINFO,                      "Failed to get tbinfo when parsing DELETE"                              },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_IMAGE,                       "Failed to parse full page write data when parsing DELETE"              },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_TUPLE,                       "Failed to get tuple data when parsing DELETE"                          },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_TUPEL_ALLOC,                 "Failed to allocate tuple space when parsing DELETE"                    },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_TUPLE_IN,                    "Failed to get passed-in tuple when parsing DELETE"                     },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_TEMP_ALLOC,                  "Failed to build tuple when parsing DELETE"                             },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_LOGICAL_FLAG,                "No tupleflag in logical mode when parsing DELETE"                      },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_LOGICAL_DATA,
     "Failed to get tuple data in logical mode when parsing DELETE"                                                                                 },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_DESC,                        "Failed to build DESC when parsing DELETE"                              },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_ATTR_TO_STR,                 "Failed to parse column data when parsing DELETE"                       },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_TBINFO,                      "Failed to get tbinfo when parsing UPDATE"                              },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_IMAGE,                       "Failed to parse full page write data when parsing UPDATE"              },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_TUPLE_RETURN,                "Failed to build return tuple when parsing UPDATE"                      },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_TUPLE_CHECK,                 "Failed to check passed-in tuple when parsing UPDATE"                   },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_GET_OLD_TUPLE,               "Failed to get old tuple when parsing UPDATE"                           },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_GET_NEW_TUPLE,               "Failed to get new tuple when parsing UPDATE"                           },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_MAKE_NEW_TUPLE_FROM_OLD,
     "Failed to merge old tuple data into new tuple when parsing UPDATE"                                                                            },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_LOGICAL_FLAG,                "No tupleflag in logical mode when parsing UPDATE"                      },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_LOGICAL_DATA,
     "Failed to get tuple data in logical mode when parsing UPDATE"                                                                                 },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_LOGICAL_GET_NEW_TUPLE_DATA,
     "Failed to get new tuple data when parsing UPDATE"                                                                                             },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_LOGICAL_MALLOC_TUPLE,
     "Failed to allocate space for tuple when parsing UPDATE"                                                                                       },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_LOGICAL_GET_OLD_TUPLE_DATA,
     "Failed to get old tuple data when parsing UPDATE"                                                                                             },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_DESC,                        "Failed to build DESC when parsing UPDATE"                              },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_OLD_VALUE_ATTR_TO_STR,
     "Failed to parse old value column data when parsing UPDATE"                                                                                    },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_NEW_VALUE_ATTR_TO_STR,
     "Failed to parse new value column data when parsing UPDATE"                                                                                    },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_FPW_GET_RETURN_TUPLE_FROM_IMAGE,
     "Failed to get full page write or build return tuple in HEAP/HEAP2 RECORD parsing with full "
     "page write but no parsing needed"                                                                                                             },
    {ERRNO_PG_PARSER_TRANS_FUNCERR_RMGR_NOT_FIND,                           "Invalid RMGR ID"                                                       },
    {ERRNO_PG_PARSER_DDLSTMT_GET_COLUMN_BY_COLNAME,                         "Error getting column value by column name in DDL parsing"              },
    {ERRNO_PG_PARSER_DDLSTMT_GET_CLASSINFO,                                 "Error getting pg_class related information in DDL parsing"             },
    {ERRNO_PG_PARSER_DDLSTMT_GET_ATTRIBUTE_LIST,                            "Error getting pg_attribute related information in DDL parsing"         },
    {ERRNO_PG_PARSER_DDLSTMT_DROP_TABLE_RELKIND_CHECK,
     "Error in key check of table type during DROP TABLE in DDL parsing"                                                                            },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_DROP_COLUMN,
     "Key parameter check is empty when parsing DROP_COLUMN in DDL parsing"                                                                         },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_RENAME_COLUMN,
     "Key parameter check is empty when parsing RENAME_COLUMN in DDL parsing"                                                                       },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_COLUMN_NOTNULL,
     "Key parameter check is empty when parsing COLUMN_NOTNULL in DDL parsing"                                                                      },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_COLUMN_NULL,
     "Key parameter check is empty when parsing COLUMN_NULL in DDL parsing"                                                                         },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_ALTER_COLUMN_TYPE,
     "Key parameter check is empty when parsing ALTER_COLUMN_TYPE in DDL parsing"                                                                   },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_ADD_DEFAULT,
     "Key parameter check is empty when parsing ADD_DEFAULT in DDL parsing"                                                                         },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_DROP_DEFAULT,
     "Key parameter check is empty when parsing DROP_DEFAULT in DDL parsing"                                                                        },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_ADD_CONSTRAINT,
     "Key parameter check is empty when parsing ADD_CONSTRAINT in DDL parsing"                                                                      },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_ADD_COLUMN1,
     "Key parameter check is empty when parsing ADD_COLUMN1 in DDL parsing"                                                                         },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_ADD_COLUMN2,
     "Key parameter check is empty when parsing ADD_COLUMN2 in DDL parsing"                                                                         },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_INDEX1,
     "Key parameter check is empty when parsing CREATE_INDEX1 in DDL parsing"                                                                       },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_INDEX2,
     "Key parameter check is empty when parsing CREATE_INDEX2 in DDL parsing"                                                                       },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_SEQUENCE,
     "Key parameter check is empty when parsing CREATE_SEQUENCE in DDL parsing"                                                                     },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_PARTITION1,
     "Key parameter check is empty when parsing CREATE_PARTITION1 in DDL parsing"                                                                   },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_PARTITION2,
     "Key parameter check is empty when parsing CREATE_PARTITION2 in DDL parsing"                                                                   },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_PARTITION3,
     "Key parameter check is empty when parsing CREATE_PARTITION3 in DDL parsing"                                                                   },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_PARTITION_SUB1,
     "Key parameter check is empty when parsing CREATE_PARTITION_SUB1 in DDL parsing"                                                               },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_PARTITION_SUB2,
     "Key parameter check is empty when parsing CREATE_PARTITION_SUB2 in DDL parsing"                                                               },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_TYPE1,
     "Key parameter check is empty when parsing CREATE_TYPE1 in DDL parsing"                                                                        },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_TYPE2,
     "Key parameter check is empty when parsing CREATE_TYPE2 in DDL parsing"                                                                        },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_DROP_INDEX,
     "Key parameter check is empty when parsing DROP_INDEX in DDL parsing"                                                                          },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_DROP_TYPE1,
     "Key parameter check is empty when parsing DROP_TYPE1 in DDL parsing"                                                                          },
    {ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_DROP_TYPE2,
     "Key parameter check is empty when parsing DROP_TYPE2 in DDL parsing"                                                                          },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_1,                                  "Error 1 occurred in JNI interface during DDL parsing"                  },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_2,                                  "Error 2 occurred in JNI interface during DDL parsing"                  },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_3,                                  "Error 3 occurred in JNI interface during DDL parsing"                  },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_4,                                  "Error 4 occurred in JNI interface during DDL parsing"                  },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_5,                                  "Error 5 occurred in JNI interface during DDL parsing"                  },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_6,                                  "Error 6 occurred in JNI interface during DDL parsing"                  },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_7,                                  "Error 7 occurred in JNI interface during DDL parsing"                  },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_8,                                  "Error 8 occurred in JNI interface during DDL parsing"                  },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_9,                                  "Error 9 occurred in JNI interface during DDL parsing"                  },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_10,                                 "Error 10 occurred in JNI interface during DDL parsing"                 },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_11,                                 "Error 11 occurred in JNI interface during DDL parsing"                 },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_12,                                 "Error 12 occurred in JNI interface during DDL parsing"                 },
    {ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_13,                                 "Error 13 occurred in JNI interface during DDL parsing"                 },
    {ERRNO_PG_PARSER_JNI_TRANSPRE_ERROR_1,                                  "Error 1 occurred in JNI interface during pre-parsing"                  },
    {ERRNO_PG_PARSER_JNI_TRANSPRE_ERROR_2,                                  "Error 2 occurred in JNI interface during pre-parsing"                  },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_1,                                  "Error 1 occurred in JNI interface during secondary parsing"            },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_2,                                  "Error 2 occurred in JNI interface during secondary parsing"            },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_3,                                  "Error 3 occurred in JNI interface during secondary parsing"            },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_4,                                  "Error 4 occurred in JNI interface during secondary parsing"            },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_5,                                  "Error 5 occurred in JNI interface during secondary parsing"            },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_6,                                  "Error 6 occurred in JNI interface during secondary parsing"            },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_7,                                  "Error 7 occurred in JNI interface during secondary parsing"            },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_8,                                  "Error 8 occurred in JNI interface during secondary parsing"            },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_9,                                  "Error 9 occurred in JNI interface during secondary parsing"            },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_10,                                 "Error 10 occurred in JNI interface during secondary parsing"           },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_11,                                 "Error 11 occurred in JNI interface during secondary parsing"           },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_12,                                 "Error 12 occurred in JNI interface during secondary parsing"           },
    {ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_13,                                 "Error 13 occurred in JNI interface during secondary parsing"           },
    {ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_1,                                "Error 1 occurred in JNI interface during out-of-line storage parsing"  },
    {ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_2,                                "Error 2 occurred in JNI interface during out-of-line storage parsing"  },
    {ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_3,                                "Error 3 occurred in JNI interface during out-of-line storage parsing"  },
    {ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_4,                                "Error 4 occurred in JNI interface during out-of-line storage parsing"  },
    {ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_5,                                "Error 5 occurred in JNI interface during out-of-line storage parsing"  },
    {ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_6,                                "Error 6 occurred in JNI interface during out-of-line storage parsing"  },
    {ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_7,                                "Error 7 occurred in JNI interface during out-of-line storage parsing"  },
    {ERRNO_PG_PARSER_PRE_STANDBY_MEMALLOC_ERROR1,                           "Memory allocation error 1 during STANDBY pre-parsing"                  },
    {ERRNO_PG_PARSER_PRE_STANDBY_MEMALLOC_ERROR2,                           "Memory allocation error 2 during STANDBY pre-parsing"                  },
    {ERRNO_PG_PARSER_PRE_FUNCERR_XLOG_RECOVERY_CHECK,                       "Parameter check failed during XLOG pre-parsing"                        },
    {ERRNO_PG_PARSER_PRE_XLOG_RECOVERY_MEMALLOC_ERROR1,                     "Memory allocation error 1 during XLOG pre-parsing"                     }
};

char* pg_parser_errno_getErrInfo(int32_t pg_parser_errno)
{
    int32_t index = 0;
    char*   errmsg_result = NULL;

    pg_parser_errno = (pg_parser_errno & ERRNO_INDEX); /* make vs studio happy */
    if (0 == (pg_parser_errno & ERRNO_MASK))
    {
        /* Return system error message */
        return strerror(errno);
    }
    for (index = 0; index < ERRNO_CNT; index++)
    {
        if (pg_parser_errno == m_errno_2_msg[index].m_errno)
        {
            errmsg_result = m_errno_2_msg[index].m_errormsg;
            break;
        }
    }
    if (NULL == errmsg_result)
    {
        return "unknown errno code";
    }

    return errmsg_result;
}
