#include "xk_pg_parser_os_incl.h"
#include "xk_pg_parser_app_incl.h"

/**
 * @brief          错误码与错误信息的对应关系
 */
typedef struct XK_PG_PARSER_ERRNO_2_MSG
{
    int32_t        m_errno;      /*!< 错误码的值 */
    char          *m_errormsg;   /*!< 错误信息 */
} xk_pg_parser_errno_2_msg;

/**
 * @brief          全部的错误码及其错误信息
 */
static xk_pg_parser_errno_2_msg m_errno_2_msg[] =
{
    {XK_ERRNO_SUCCESS,                              "成功"},
    {XK_ERRNO_PG_PARSER_PRE_USELESS,                "缺少预解析函数"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_BEGIN,           "内存错误码开始标志"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_00, "invalid record预解析分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_01, "heap_insert record预解析分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_02, "heap_update record预解析分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_03, "heap_hot_update record预解析分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_04, "heap_delete record预解析分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_05, "heap2_mutli_insert record预解析分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_06, "xact_commit record预解析分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_07, "xact_abort record预解析分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_08, "xact_switch record预解析分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_09, "xlog_checkpoint_online record预解析分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_RECORD_0A, "xlog_checkpoint_shutdown record预解析分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_DECODESTATE, "record state分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_BLOCK,     "解码record时, 全页写数据分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_MAINDATA,  "解码record时, maindata分配内存失败"},
    {XK_ERRNO_PG_PARSER_PRE_MEMERR_ALLOC_IMAGE_FPW, "xk_pg_parser_check_fpw 分配全页写内存失败"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_00, "解析时, 分配内存失败 位置: 00"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_01, "解析时, 分配内存失败 位置: 01"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_02, "解析时, 分配内存失败 位置: 02"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_03, "解析时, 分配内存失败 位置: 03"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_04, "解析时, 分配内存失败 位置: 04"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_05, "解析时, 分配内存失败 位置: 05"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_06, "解析时, 分配内存失败 位置: 06"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_07, "解析时, 分配内存失败 位置: 07"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_08, "解析时, 分配内存失败 位置: 08"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_09, "解析时, 分配内存失败 位置: 09"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0A, "解析时, 分配内存失败 位置: 0A"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0B, "解析时, 分配内存失败 位置: 0B"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0C, "解析时, 分配内存失败 位置: 0C"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0D, "解析时, 分配内存失败 位置: 0D"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0E, "解析时, 分配内存失败 位置: 0E"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_0F, "解析时, 分配内存失败 位置: 0F"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_10, "解析时, 分配内存失败 位置: 10"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_11, "解析时, 分配内存失败 位置: 11"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_12, "解析时, 分配内存失败 位置: 12"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_13, "解析时, 分配内存失败 位置: 13"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_14, "解析时, 分配内存失败 位置: 14"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_15, "解析时, 分配内存失败 位置: 15"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_16, "解析时, 分配内存失败 位置: 16"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_17, "解析时, 分配内存失败 位置: 17"},
    {XK_ERRNO_PG_PARSER_TRANS_MEMERR_ALLOC_18, "解析时, 分配内存失败 位置: 18"},
    {XK_ERRNO_PG_PARSER_EXTERNAL_MEMERR_ALLOC_00, "行外存储数据解析时, 分配内存失败 位置: 00"},
    {XK_ERRNO_PG_PARSER_EXTERNAL_MEMERR_ALLOC_01, "行外存储数据解析时, 分配内存失败 位置: 01"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_00, "DDL解析时, 分配内存失败, 位置: 00"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_01, "DDL解析时, 分配内存失败, 位置: 01"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_02, "DDL解析时, 分配内存失败, 位置: 02"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_03, "DDL解析时, 分配内存失败, 位置: 03"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_04, "DDL解析时, 分配内存失败, 位置: 04"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_05, "DDL解析时, 分配内存失败, 位置: 05"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_06, "DDL解析时, 分配内存失败, 位置: 06"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_07, "DDL解析时, 分配内存失败, 位置: 07"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_08, "DDL解析时, 分配内存失败, 位置: 08"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_09, "DDL解析时, 分配内存失败, 位置: 09"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0A, "DDL解析时, 分配内存失败, 位置: 0A"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0B, "DDL解析时, 分配内存失败, 位置: 0B"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0C, "DDL解析时, 分配内存失败, 位置: 0C"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0D, "DDL解析时, 分配内存失败, 位置: 0D"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0E, "DDL解析时, 分配内存失败, 位置: 0E"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_0F, "DDL解析时, 分配内存失败, 位置: 0F"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_10, "DDL解析时, 分配内存失败, 位置: 10"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_11, "DDL解析时, 分配内存失败, 位置: 11"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_12, "DDL解析时, 分配内存失败, 位置: 12"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_13, "DDL解析时, 分配内存失败, 位置: 13"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_14, "DDL解析时, 分配内存失败, 位置: 14"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_15, "DDL解析时, 分配内存失败, 位置: 15"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_16, "DDL解析时, 分配内存失败, 位置: 16"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_17, "DDL解析时, 分配内存失败, 位置: 17"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_18, "DDL解析时, 分配内存失败, 位置: 18"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_19, "DDL解析时, 分配内存失败, 位置: 19"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1A, "DDL解析时, 分配内存失败, 位置: 1A"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1B, "DDL解析时, 分配内存失败, 位置: 1B"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1C, "DDL解析时, 分配内存失败, 位置: 1C"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1D, "DDL解析时, 分配内存失败, 位置: 1D"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1E, "DDL解析时, 分配内存失败, 位置: 1E"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_1F, "DDL解析时, 分配内存失败, 位置: 1F"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_20, "DDL解析时, 分配内存失败, 位置: 20"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_21, "DDL解析时, 分配内存失败, 位置: 21"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_22, "DDL解析时, 分配内存失败, 位置: 22"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_23, "DDL解析时, 分配内存失败, 位置: 23"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_24, "DDL解析时, 分配内存失败, 位置: 24"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_25, "DDL解析时, 分配内存失败, 位置: 25"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_26, "DDL解析时, 分配内存失败, 位置: 26"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_27, "DDL解析时, 分配内存失败, 位置: 27"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_28, "DDL解析时, 分配内存失败, 位置: 28"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_29, "DDL解析时, 分配内存失败, 位置: 29"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2A, "DDL解析时, 分配内存失败, 位置: 2A"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2B, "DDL解析时, 分配内存失败, 位置: 2B"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2C, "DDL解析时, 分配内存失败, 位置: 2C"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2D, "DDL解析时, 分配内存失败, 位置: 2D"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2E, "DDL解析时, 分配内存失败, 位置: 2E"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_2F, "DDL解析时, 分配内存失败, 位置: 2F"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_30, "DDL解析时, 分配内存失败, 位置: 30"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_31, "DDL解析时, 分配内存失败, 位置: 31"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_32, "DDL解析时, 分配内存失败, 位置: 32"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_33, "DDL解析时, 分配内存失败, 位置: 33"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_34, "DDL解析时, 分配内存失败, 位置: 34"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_35, "DDL解析时, 分配内存失败, 位置: 35"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_36, "DDL解析时, 分配内存失败, 位置: 36"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_37, "DDL解析时, 分配内存失败, 位置: 37"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_38, "DDL解析时, 分配内存失败, 位置: 38"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_39, "DDL解析时, 分配内存失败, 位置: 39"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3A, "DDL解析时, 分配内存失败, 位置: 3A"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3B, "DDL解析时, 分配内存失败, 位置: 3B"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3C, "DDL解析时, 分配内存失败, 位置: 3C"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3D, "DDL解析时, 分配内存失败, 位置: 3D"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3E, "DDL解析时, 分配内存失败, 位置: 3E"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_3F, "DDL解析时, 分配内存失败, 位置: 3F"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_40, "DDL解析时, 分配内存失败, 位置: 40"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_41, "DDL解析时, 分配内存失败, 位置: 41"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_42, "DDL解析时, 分配内存失败, 位置: 42"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_43, "DDL解析时, 分配内存失败, 位置: 43"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_44, "DDL解析时, 分配内存失败, 位置: 44"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_45, "DDL解析时, 分配内存失败, 位置: 45"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_46, "DDL解析时, 分配内存失败, 位置: 46"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_47, "DDL解析时, 分配内存失败, 位置: 47"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_48, "DDL解析时, 分配内存失败, 位置: 48"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_49, "DDL解析时, 分配内存失败, 位置: 49"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4A, "DDL解析时, 分配内存失败, 位置: 4A"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4B, "DDL解析时, 分配内存失败, 位置: 4B"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4C, "DDL解析时, 分配内存失败, 位置: 4C"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4D, "DDL解析时, 分配内存失败, 位置: 4D"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4E, "DDL解析时, 分配内存失败, 位置: 4E"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_4F, "DDL解析时, 分配内存失败, 位置: 4F"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_50, "DDL解析时, 分配内存失败, 位置: 50"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_51, "DDL解析时, 分配内存失败, 位置: 51"},
    {XK_ERRNO_PG_PARSER_DDL_MEMERR_ALLOC_52, "DDL解析时, 分配内存失败, 位置: 52"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_PRE_CHECK, "预解析时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_PRE_DECODE,         "预解析时, RECORD解码失败"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_PRE_PARAM_CHECK,    "预解析时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_HEAP_INSERT_CHECK,  "预解析INSERT时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_HEAP2_MINSERT_CHECK, "预解析MULTI INSERT时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_HEAP_DELETE_CHECK,  "预解析DELETE时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_HEAP_UPDATE_CHECK,  "预解析UPDATE时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_HEAP_HUPDATE_CHECK, "预解析HOT UPDATE时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_XACT_COMMIT_CHECK,  "预解析COMMIT时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_XACT_ABORT_CHECK,   "预解析ABORT时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_XLOG_CKPS_CHECK,    "预解析CHECKPOINT SHUTDOWN时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_XLOG_CKPO_CHECK,    "预解析CHECKPOINT ONLINE时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_XLOG_SWITCH_CHECK,  "预解析SWITCH RECORD时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_DECODE_RECORD_BLOCKID_CHECK,    "解析record时block_id的解析结果出错"},
    {XK_ERRNO_PG_PARSER_DECODE_RECORD_NODATA,           "解析record时设置了data标记, 但record中没有data数据"},
    {XK_ERRNO_PG_PARSER_DECODE_RECORD_DATASET,          "解析record时record没有设置DATA标记, 但有data数据存在"},
    {XK_ERRNO_PG_PARSER_DECODE_RECORD_HASHOLE,          "解析record时record没有设置hole标记, 但hole的长度>0"},
    {XK_ERRNO_PG_PARSER_DECODE_RECORD_HASCOMPRESSED,    "解析record时record设置了压缩标记, 但长度值无效"},
    {XK_ERRNO_PG_PARSER_DECODE_RECORD_COMPRESSED_LENGTH, "解析record时record的压缩或空洞长度无效"},
    {XK_ERRNO_PG_PARSER_DECODE_RECORD_NOSAMEREL,        "解析record时record设置了same rel, 但没有前一个rel数据"},
    {XK_ERRNO_PG_PARSER_DECODE_RECORD_INVALID_BLOCKID,  "解析record时recordd的blockid无效"},
    {XK_ERRNO_PG_PARSER_DECODE_RECORD_SHORT,            "解析record时record解析完成后数据长度与累计值不符"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_CHECK,   "解析INSERT时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MINSERT_CHECK,  "解析MULTI INSERT时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_CHECK,   "解析UPDATE时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_CHECK,   "解析DELETE时, 检查到了无效的传入参数"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_TRANS_DECODE, "解析时, RECORD解码失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_TBINFO,               "解析INSERT时, 获取tbinfo失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_GET_IMAGE,            "解析INSERT时, 解析全页写数据失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_GET_TUPLE,            "解析INSERT时, 获取tuple data失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_GET_TEMP_TUPLE,       "解析INSERT时, 构建tuple失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_GET_TUPLE2,           "解析INSERT时, 获取tuple data失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_GET_TEMP_TUPLE2,      "解析INSERT时, 构建tuple失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_LOGICAL_NEWTUPLE_FLAG, "解析INSERT时, logical模式下, 没有tupleflag"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_LOGICAL_GET_TUPLE,    "解析INSERT时, logical模式下, 获取tuple data失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_LOGICAL_GET_TEMPTUPLE, "解析INSERT时, logical模式下, 构建tuple失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_MAKE_DESC,            "解析INSERT时, 构建DESC失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_INSERT_CONVERT_ATTR_TO_CHAR, "解析INSERT时, 解析列数据失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_TBINFO,        "解析MULTI INSERT时, 获取tbinfo失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_GET_IMAGE,     "解析MULTI INSERT时, 解析全页写数据失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_GET_TUPLE,     "解析MULTI INSERT时, 获取tuple data失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_GET_TEMP_TUPLE, "解析MULTI INSERT时, 构建tuple失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_LOGICAL_NEW_FLAG, "解析MULTI INSERT时, logical模式下, 没有tupleflag"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_LOGICAL_DATA,  "解析MULTI INSERT时, logical模式下, 获取tuple data失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_MAKE_DESC,     "解析MULTI INSERT时, 构建DESC失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_MULTI_INSERT_CONVERT_ATTR_TO_CHAR, "解析MULTI INSERT时, 解析列数据失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_TBINFO,               "解析DELETE时, 获取tbinfo失败" },
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_IMAGE,                "解析DELETE时, 解析全页写数据失败" },
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_TUPLE,                "解析DELETE时, 获取tuple data失败" },
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_TUPEL_ALLOC,          "解析DELETE时, 构建tuple空间失败" },
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_TUPLE_IN,             "解析DELETE时, 获取传入的tuple失败" },
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_TEMP_ALLOC,           "解析DELETE时, 构建tuple失败" },
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_LOGICAL_FLAG,         "解析DELETE时, logical模式下, 没有tupleflag" },
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_LOGICAL_DATA,         "解析DELETE时, logical模式下, 获取tuple data失败" },
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_DESC,                 "解析DELETE时, 构建DESC失败" },
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_DELETE_ATTR_TO_STR,          "解析DELETE时, 解析列数据失败" },
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_TBINFO,               "解析UPDATE时, 获取tbinfo失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_IMAGE,                "解析UPDATE时, 解析全页写数据失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_TUPLE_RETURN,         "解析UPDATE时, 构建返回tuple失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_TUPLE_CHECK,          "解析UPDATE时, 检查传入的tuple失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_GET_OLD_TUPLE,        "解析UPDATE时, 获取旧tuple失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_GET_NEW_TUPLE,        "解析UPDATE时, 获取新tuple失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_MAKE_NEW_TUPLE_FROM_OLD, "解析UPDATE时, 将旧tuple数据合并进新tuple中失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_LOGICAL_FLAG,         "解析UPDATE时, logical模式下, 没有tupleflag"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_LOGICAL_DATA,         "解析UPDATE时, logical模式下, 获取tuple data失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_LOGICAL_GET_NEW_TUPLE_DATA, "解析UPDATE时, 获取新tuple数据失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_LOGICAL_MALLOC_TUPLE, "解析UPDATE时, 为tuple开辟空间失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_LOGICAL_GET_OLD_TUPLE_DATA, "解析UPDATE时, 获取旧tuple数据失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_DESC,                 "解析UPDATE时, 构建DESC失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_OLD_VALUE_ATTR_TO_STR, "解析UPDATE时, 旧值解析列数据失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP_UPDATE_NEW_VALUE_ATTR_TO_STR, "解析UPDATE时, 新值解析列数据失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_HEAP2_FPW_GET_RETURN_TUPLE_FROM_IMAGE, "在拥有全页写但无需解析的解析HEAP/HEAP2 RECORD中, 获取全页写或构建返回tuple失败"},
    {XK_ERRNO_PG_PARSER_TRANS_FUNCERR_RMGR_NOT_FIND,        "RMGR ID 无效"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_GET_COLUMN_BY_COLNAME,      "在DDL解析中, 通过列名获取列值过程出错"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_GET_CLASSINFO,              "在DDL解析中, 获取pg_class相关信息出错"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_GET_ATTRIBUTE_LIST,         "在DDL解析中, 获取pg_attribute相关信息出错"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_DROP_TABLE_RELKIND_CHECK,   "在DDL解析中, DROP TABLE时对表类型关键检查出错"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_DROP_COLUMN,           "在DDL解析中, 解析DROP_COLUMN时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_RENAME_COLUMN,         "在DDL解析中, 解析RENAME_COLUMN时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_COLUMN_NOTNULL,        "在DDL解析中, 解析COLUMN_NOTNULL时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_COLUMN_NULL,           "在DDL解析中, 解析COLUMN_NULL时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_ALTER_COLUMN_TYPE,     "在DDL解析中, 解析ALTER_COLUMN_TYPE时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_ADD_DEFAULT,           "在DDL解析中, 解析ADD_DEFAULT时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_DROP_DEFAULT,          "在DDL解析中, 解析DROP_DEFAULT时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_ADD_CONSTRAINT,        "在DDL解析中, 解析ADD_CONSTRAINT时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_ADD_COLUMN1,           "在DDL解析中, 解析ADD_COLUMN1时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_ADD_COLUMN2,           "在DDL解析中, 解析ADD_COLUMN2时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_INDEX1,         "在DDL解析中, 解析CREATE_INDEX1时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_INDEX2,         "在DDL解析中, 解析CREATE_INDEX2时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_SEQUENCE,       "在DDL解析中, 解析CREATE_SEQUENCE时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_PARTITION1,     "在DDL解析中, 解析CREATE_PARTITION1时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_PARTITION2,     "在DDL解析中, 解析CREATE_PARTITION2时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_PARTITION3,     "在DDL解析中, 解析CREATE_PARTITION3时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_PARTITION_SUB1, "在DDL解析中, 解析CREATE_PARTITION_SUB1时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_PARTITION_SUB2, "在DDL解析中, 解析CREATE_PARTITION_SUB2时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_TYPE1,          "在DDL解析中, 解析CREATE_TYPE1时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_CREATE_TYPE2,          "在DDL解析中, 解析CREATE_TYPE2时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_DROP_INDEX,            "在DDL解析中, 解析DROP_INDEX时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_DROP_TYPE1,            "在DDL解析中, 解析DROP_TYPE1时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_DDLSTMT_CHECKPARAM_DROP_TYPE2,            "在DDL解析中, 解析DROP_TYPE2时关键参数检查为空"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_1,                 "在DDL解析中, JNI接口中出现错误1"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_2,                 "在DDL解析中, JNI接口中出现错误2"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_3,                 "在DDL解析中, JNI接口中出现错误3"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_4,                 "在DDL解析中, JNI接口中出现错误4"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_5,                 "在DDL解析中, JNI接口中出现错误5"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_6,                 "在DDL解析中, JNI接口中出现错误6"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_7,                 "在DDL解析中, JNI接口中出现错误7"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_8,                 "在DDL解析中, JNI接口中出现错误8"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_9,                 "在DDL解析中, JNI接口中出现错误9"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_10,                "在DDL解析中, JNI接口中出现错误10"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_11,                "在DDL解析中, JNI接口中出现错误11"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_12,                "在DDL解析中, JNI接口中出现错误12"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSDDL_ERROR_13,                "在DDL解析中, JNI接口中出现错误13"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSPRE_ERROR_1,                 "在预解析中, JNI接口出现错误1"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSPRE_ERROR_2,                 "在预解析中, JNI接口出现错误2"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_1,                 "在二次解析中, JNI接口出现错误1"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_2,                 "在二次解析中, JNI接口出现错误2"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_3,                 "在二次解析中, JNI接口出现错误3"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_4,                 "在二次解析中, JNI接口出现错误4"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_5,                 "在二次解析中, JNI接口出现错误5"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_6,                 "在二次解析中, JNI接口出现错误6"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_7,                 "在二次解析中, JNI接口出现错误7"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_8,                 "在二次解析中, JNI接口出现错误8"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_9,                 "在二次解析中, JNI接口出现错误9"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_10,                "在二次解析中, JNI接口出现错误10"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_11,                "在二次解析中, JNI接口出现错误11"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_12,                "在二次解析中, JNI接口出现错误12"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSROW_ERROR_13,                "在二次解析中, JNI接口出现错误13"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_1,               "在行外存储解析中, JNI接口出现错误1"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_2,               "在行外存储解析中, JNI接口出现错误2"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_3,               "在行外存储解析中, JNI接口出现错误3"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_4,               "在行外存储解析中, JNI接口出现错误4"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_5,               "在行外存储解析中, JNI接口出现错误5"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_6,               "在行外存储解析中, JNI接口出现错误6"},
    {XK_ERRNO_PG_PARSER_JNI_TRANSTOAST_ERROR_7,               "在行外存储解析中, JNI接口出现错误7"},
    {XK_ERRNO_PG_PARSER_PRE_STANDBY_MEMALLOC_ERROR1,          "在预解析STANDBY中, 内存分配错误1"},
    {XK_ERRNO_PG_PARSER_PRE_STANDBY_MEMALLOC_ERROR2,          "在预解析STANDBY中, 内存分配错误2"},
    {XK_ERRNO_PG_PARSER_PRE_FUNCERR_XLOG_RECOVERY_CHECK,      "在预解析XLOG中, 参数检查失败"},
    {XK_ERRNO_PG_PARSER_PRE_XLOG_RECOVERY_MEMALLOC_ERROR1,    "在预解析XLOG中, 内存分配错误1"}
};

char *xk_pg_parser_errno_getErrInfo(int32_t xk_pg_parser_errno)
{
    int32_t index = 0;
    char *errmsg_result = NULL;

    xk_pg_parser_errno = (xk_pg_parser_errno & XK_ERRNO_INDEX);     /* make vs studio happy */
    if (0 == (xk_pg_parser_errno & XK_ERRNO_MASK))
    {
        /* 返回系统错误信息 */
        return strerror(errno);
    }
    for (index = 0; index < XK_ERRNO_CNT; index++)
    {
        if (xk_pg_parser_errno == m_errno_2_msg[index].m_errno)
        {
            errmsg_result = m_errno_2_msg[index].m_errormsg;
            break;
        }
    }
    if (NULL == errmsg_result)
        return "unknown errno code";

    return errmsg_result;
}
