#ifndef XK_PG_PARSER_TRANS_TRANSREC_RMGR_H
#define XK_PG_PARSER_TRANS_TRANSREC_RMGR_H

#define XK_PG_PARSER_TRANS_TRANSREC_XLR_INFO_MASK             0x0F
#define XK_PG_PARSER_TRANS_TRANSREC_XLR_RMGR_INFO_MASK        0xF0

/*-------------------   RMGR     begin   ---------------------*/
typedef enum XK_PG_PARSER_TRANS_RMGR_ENUM
{
    XK_PG_PARSER_TRANSLOG_RMGR_XLOG_ID = 0,
    XK_PG_PARSER_TRANSLOG_RMGR_XACT_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_SMGR_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_CLOG_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_DBASE_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_TBLSPC_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_MULTIXACT_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_RELMAP_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_STANDBY_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_HEAP2_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_HEAP_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_BTREE_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_HASH_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_GIN_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_GIST_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_SEQ_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_SPGIST_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_BRIN_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_COMMIT_TS_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_REPLORIGIN_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_GENERIC_ID,
    XK_PG_PARSER_TRANSLOG_RMGR_LOGICALMSG_ID
} xk_pg_parser_trans_rmgr_enum;

/*-------------------   RMGR     end   ---------------------*/
#endif
