#ifndef XK_PG_PARSER_SYSDICT_PG_TYPE_H
#define XK_PG_PARSER_SYSDICT_PG_TYPE_H

#define TypeRelationId 1247
#define TypeRelationIdChar "1247"
#define TypeRelation_Rowtype_Id 71

typedef struct XK_PG_PARSER_SYSDICT_PGTYPE
{
#if XK_PG_VERSION_NUM >= 120000
    uint32_t                    oid;
#endif
    xk_pg_parser_NameData       typname;
    int16_t                     typlen;
    bool                        typbyval;
    char                        typtype;
    char                        typdelim;
    uint32_t                    typelem;
    uint32_t                    typoutput;
    uint32_t                    typrelid;
    char                        typalign;
    char                        typstorage;
} xk_pg_parser_sysdict_pgtype;

typedef xk_pg_parser_sysdict_pgtype *xk_pg_sysdict_Form_pg_type;

#define  XK_PG_SYSDICT_TYPTYPE_BASE             'b' /* base type (ordinary scalar type) */
#define  XK_PG_SYSDICT_TYPTYPE_COMPOSITE        'c' /* composite (e.g., table's rowtype) */
#define  XK_PG_SYSDICT_TYPTYPE_DOMAIN           'd' /* domain over another type */
#define  XK_PG_SYSDICT_TYPTYPE_ENUM             'e' /* enumerated type */
#define  XK_PG_SYSDICT_TYPTYPE_PSEUDO           'p' /* pseudo-type */
#define  XK_PG_SYSDICT_TYPTYPE_RANGE            'r' /* range type */
#define  XK_PG_SYSDICT_TYPTYPE_NULL             'n' /* 指空类型, 自行添加, 非pg原生 */

#define  XK_PG_SYSDICT_TYPCATEGORY_INVALID      '\0'    /* not an allowed category */
#define  XK_PG_SYSDICT_TYPCATEGORY_ARRAY        'A'
#define  XK_PG_SYSDICT_TYPCATEGORY_BOOLEAN      'B'
#define  XK_PG_SYSDICT_TYPCATEGORY_COMPOSITE    'C'
#define  XK_PG_SYSDICT_TYPCATEGORY_DATETIME     'D'
#define  XK_PG_SYSDICT_TYPCATEGORY_ENUM         'E'
#define  XK_PG_SYSDICT_TYPCATEGORY_GEOMETRIC    'G'
#define  XK_PG_SYSDICT_TYPCATEGORY_NETWORK      'I' /* think INET */
#define  XK_PG_SYSDICT_TYPCATEGORY_NUMERIC      'N'
#define  XK_PG_SYSDICT_TYPCATEGORY_PSEUDOTYPE   'P'
#define  XK_PG_SYSDICT_TYPCATEGORY_RANGE        'R'
#define  XK_PG_SYSDICT_TYPCATEGORY_STRING       'S'
#define  XK_PG_SYSDICT_TYPCATEGORY_TIMESPAN     'T'
#define  XK_PG_SYSDICT_TYPCATEGORY_USER         'U'
#define  XK_PG_SYSDICT_TYPCATEGORY_BITSTRING    'V' /* er ... "varbit"? */
#define  XK_PG_SYSDICT_TYPCATEGORY_UNKNOWN      'X'

/* Is a type OID a polymorphic pseudotype?    (Beware of multiple evaluation) */
#define IsPolymorphicType(typid)  \
    ((typid) == XK_PG_SYSDICT_ANYELEMENTOID || \
     (typid) == XK_PG_SYSDICT_ANYARRAYOID || \
     (typid) == XK_PG_SYSDICT_ANYNONARRAYOID || \
     (typid) == XK_PG_SYSDICT_ANYENUMOID || \
     (typid) == XK_PG_SYSDICT_ANYRANGEOID)

#if XK_PG_VERSION_NUM >= 130000
/* Code not part of polymorphic type resolution should not use these macros: */
#define IsPolymorphicTypeFamily1(typid)  \
    ((typid) == XK_PG_SYSDICT_ANYELEMENTOID || \
     (typid) == XK_PG_SYSDICT_ANYARRAYOID || \
     (typid) == XK_PG_SYSDICT_ANYNONARRAYOID || \
     (typid) == XK_PG_SYSDICT_ANYENUMOID || \
     (typid) == XK_PG_SYSDICT_ANYRANGEOID)

#define IsPolymorphicTypeFamily2(typid)  \
    ((typid) == XK_PG_SYSDICT_ANYCOMPATIBLEOID || \
     (typid) == XK_PG_SYSDICT_ANYCOMPATIBLEARRAYOID || \
     (typid) == XK_PG_SYSDICT_ANYCOMPATIBLENONARRAYOID || \
     (typid) == XK_PG_SYSDICT_ANYCOMPATIBLERANGEOID)
#endif

#if XK_PG_VERSION_NUM >= 150000
#define XK_PG_SYSDICT_CASHOID   XK_PG_SYSDICT_MONEYOID
#define XK_PG_SYSDICT_LSNOID    XK_PG_SYSDICT_PG_LSNOID

#define XK_PG_SYSDICT_BOOLOID 16
#define XK_PG_SYSDICT_BYTEAOID 17
#define XK_PG_SYSDICT_CHAROID 18
#define XK_PG_SYSDICT_NAMEOID 19
#define XK_PG_SYSDICT_INT8OID 20
#define XK_PG_SYSDICT_INT2OID 21
#define XK_PG_SYSDICT_INT2VECTOROID 22
#define XK_PG_SYSDICT_INT4OID 23
#define XK_PG_SYSDICT_REGPROCOID 24
#define XK_PG_SYSDICT_TEXTOID 25
#define XK_PG_SYSDICT_OIDOID 26
#define XK_PG_SYSDICT_TIDOID 27
#define XK_PG_SYSDICT_XIDOID 28
#define XK_PG_SYSDICT_CIDOID 29
#define XK_PG_SYSDICT_OIDVECTOROID 30
#define XK_PG_SYSDICT_JSONOID 114
#define XK_PG_SYSDICT_XMLOID 142
#define XK_PG_SYSDICT_PG_NODE_TREEOID 194
#define XK_PG_SYSDICT_PG_NDISTINCTOID 3361
#define XK_PG_SYSDICT_PG_DEPENDENCIESOID 3402
#define XK_PG_SYSDICT_PG_MCV_LISTOID 5017
#define XK_PG_SYSDICT_PG_DDL_COMMANDOID 32
#define XK_PG_SYSDICT_XID8OID 5069
#define XK_PG_SYSDICT_POINTOID 600
#define XK_PG_SYSDICT_LSEGOID 601
#define XK_PG_SYSDICT_PATHOID 602
#define XK_PG_SYSDICT_BOXOID 603
#define XK_PG_SYSDICT_POLYGONOID 604
#define XK_PG_SYSDICT_LINEOID 628
#define XK_PG_SYSDICT_FLOAT4OID 700
#define XK_PG_SYSDICT_FLOAT8OID 701
#define XK_PG_SYSDICT_UNKNOWNOID 705
#define XK_PG_SYSDICT_CIRCLEOID 718
#define XK_PG_SYSDICT_MONEYOID 790
#define XK_PG_SYSDICT_MACADDROID 829
#define XK_PG_SYSDICT_INETOID 869
#define XK_PG_SYSDICT_CIDROID 650
#define XK_PG_SYSDICT_MACADDR8OID 774
#define XK_PG_SYSDICT_ACLITEMOID 1033
#define XK_PG_SYSDICT_BPCHAROID 1042
#define XK_PG_SYSDICT_VARCHAROID 1043
#define XK_PG_SYSDICT_DATEOID 1082
#define XK_PG_SYSDICT_TIMEOID 1083
#define XK_PG_SYSDICT_TIMESTAMPOID 1114
#define XK_PG_SYSDICT_TIMESTAMPTZOID 1184
#define XK_PG_SYSDICT_INTERVALOID 1186
#define XK_PG_SYSDICT_TIMETZOID 1266
#define XK_PG_SYSDICT_BITOID 1560
#define XK_PG_SYSDICT_VARBITOID 1562
#define XK_PG_SYSDICT_NUMERICOID 1700
#define XK_PG_SYSDICT_REFCURSOROID 1790
#define XK_PG_SYSDICT_REGPROCEDUREOID 2202
#define XK_PG_SYSDICT_REGOPEROID 2203
#define XK_PG_SYSDICT_REGOPERATOROID 2204
#define XK_PG_SYSDICT_REGCLASSOID 2205
#define XK_PG_SYSDICT_REGCOLLATIONOID 4191
#define XK_PG_SYSDICT_REGTYPEOID 2206
#define XK_PG_SYSDICT_REGROLEOID 4096
#define XK_PG_SYSDICT_REGNAMESPACEOID 4089
#define XK_PG_SYSDICT_UUIDOID 2950
#define XK_PG_SYSDICT_PG_LSNOID 3220
#define XK_PG_SYSDICT_TSVECTOROID 3614
#define XK_PG_SYSDICT_GTSVECTOROID 3642
#define XK_PG_SYSDICT_TSQUERYOID 3615
#define XK_PG_SYSDICT_REGCONFIGOID 3734
#define XK_PG_SYSDICT_REGDICTIONARYOID 3769
#define XK_PG_SYSDICT_JSONBOID 3802
#define XK_PG_SYSDICT_JSONPATHOID 4072
#define XK_PG_SYSDICT_TXID_SNAPSHOTOID 2970
#define XK_PG_SYSDICT_PG_SNAPSHOTOID 5038
#define XK_PG_SYSDICT_INT4RANGEOID 3904
#define XK_PG_SYSDICT_NUMRANGEOID 3906
#define XK_PG_SYSDICT_TSRANGEOID 3908
#define XK_PG_SYSDICT_TSTZRANGEOID 3910
#define XK_PG_SYSDICT_DATERANGEOID 3912
#define XK_PG_SYSDICT_INT8RANGEOID 3926
#define XK_PG_SYSDICT_INT4MULTIRANGEOID 4451
#define XK_PG_SYSDICT_NUMMULTIRANGEOID 4532
#define XK_PG_SYSDICT_TSMULTIRANGEOID 4533
#define XK_PG_SYSDICT_TSTZMULTIRANGEOID 4534
#define XK_PG_SYSDICT_DATEMULTIRANGEOID 4535
#define XK_PG_SYSDICT_INT8MULTIRANGEOID 4536
#define XK_PG_SYSDICT_RECORDOID 2249
#define XK_PG_SYSDICT_RECORDARRAYOID 2287
#define XK_PG_SYSDICT_CSTRINGOID 2275
#define XK_PG_SYSDICT_ANYOID 2276
#define XK_PG_SYSDICT_ANYARRAYOID 2277
#define XK_PG_SYSDICT_VOIDOID 2278
#define XK_PG_SYSDICT_TRIGGEROID 2279
#define XK_PG_SYSDICT_EVENT_TRIGGEROID 3838
#define XK_PG_SYSDICT_LANGUAGE_HANDLEROID 2280
#define XK_PG_SYSDICT_INTERNALOID 2281
#define XK_PG_SYSDICT_ANYELEMENTOID 2283
#define XK_PG_SYSDICT_ANYNONARRAYOID 2776
#define XK_PG_SYSDICT_ANYENUMOID 3500
#define XK_PG_SYSDICT_FDW_HANDLEROID 3115
#define XK_PG_SYSDICT_INDEX_AM_HANDLEROID 325
#define XK_PG_SYSDICT_TSM_HANDLEROID 3310
#define XK_PG_SYSDICT_TABLE_AM_HANDLEROID 269
#define XK_PG_SYSDICT_ANYRANGEOID 3831
#define XK_PG_SYSDICT_ANYCOMPATIBLEOID 5077
#define XK_PG_SYSDICT_ANYCOMPATIBLEARRAYOID 5078
#define XK_PG_SYSDICT_ANYCOMPATIBLENONARRAYOID 5079
#define XK_PG_SYSDICT_ANYCOMPATIBLERANGEOID 5080
#define XK_PG_SYSDICT_ANYMULTIRANGEOID 4537
#define XK_PG_SYSDICT_ANYCOMPATIBLEMULTIRANGEOID 4538
#define XK_PG_SYSDICT_PG_BRIN_BLOOM_SUMMARYOID 4600
#define XK_PG_SYSDICT_PG_BRIN_MINMAX_MULTI_SUMMARYOID 4601
#define XK_PG_SYSDICT_BOOLARRAYOID 1000
#define XK_PG_SYSDICT_BYTEAARRAYOID 1001
#define XK_PG_SYSDICT_CHARARRAYOID 1002
#define XK_PG_SYSDICT_NAMEARRAYOID 1003
#define XK_PG_SYSDICT_INT8ARRAYOID 1016
#define XK_PG_SYSDICT_INT2ARRAYOID 1005
#define XK_PG_SYSDICT_INT2VECTORARRAYOID 1006
#define XK_PG_SYSDICT_INT4ARRAYOID 1007
#define XK_PG_SYSDICT_REGPROCARRAYOID 1008
#define XK_PG_SYSDICT_TEXTARRAYOID 1009
#define XK_PG_SYSDICT_OIDARRAYOID 1028
#define XK_PG_SYSDICT_TIDARRAYOID 1010
#define XK_PG_SYSDICT_XIDARRAYOID 1011
#define XK_PG_SYSDICT_CIDARRAYOID 1012
#define XK_PG_SYSDICT_OIDVECTORARRAYOID 1013
#define XK_PG_SYSDICT_PG_TYPEARRAYOID 210
#define XK_PG_SYSDICT_PG_ATTRIBUTEARRAYOID 270
#define XK_PG_SYSDICT_PG_PROCARRAYOID 272
#define XK_PG_SYSDICT_PG_CLASSARRAYOID 273
#define XK_PG_SYSDICT_JSONARRAYOID 199
#define XK_PG_SYSDICT_XMLARRAYOID 143
#define XK_PG_SYSDICT_XID8ARRAYOID 271
#define XK_PG_SYSDICT_POINTARRAYOID 1017
#define XK_PG_SYSDICT_LSEGARRAYOID 1018
#define XK_PG_SYSDICT_PATHARRAYOID 1019
#define XK_PG_SYSDICT_BOXARRAYOID 1020
#define XK_PG_SYSDICT_POLYGONARRAYOID 1027
#define XK_PG_SYSDICT_LINEARRAYOID 629
#define XK_PG_SYSDICT_FLOAT4ARRAYOID 1021
#define XK_PG_SYSDICT_FLOAT8ARRAYOID 1022
#define XK_PG_SYSDICT_CIRCLEARRAYOID 719
#define XK_PG_SYSDICT_MONEYARRAYOID 791
#define XK_PG_SYSDICT_MACADDRARRAYOID 1040
#define XK_PG_SYSDICT_INETARRAYOID 1041
#define XK_PG_SYSDICT_CIDRARRAYOID 651
#define XK_PG_SYSDICT_MACADDR8ARRAYOID 775
#define XK_PG_SYSDICT_ACLITEMARRAYOID 1034
#define XK_PG_SYSDICT_BPCHARARRAYOID 1014
#define XK_PG_SYSDICT_VARCHARARRAYOID 1015
#define XK_PG_SYSDICT_DATEARRAYOID 1182
#define XK_PG_SYSDICT_TIMEARRAYOID 1183
#define XK_PG_SYSDICT_TIMESTAMPARRAYOID 1115
#define XK_PG_SYSDICT_TIMESTAMPTZARRAYOID 1185
#define XK_PG_SYSDICT_INTERVALARRAYOID 1187
#define XK_PG_SYSDICT_TIMETZARRAYOID 1270
#define XK_PG_SYSDICT_BITARRAYOID 1561
#define XK_PG_SYSDICT_VARBITARRAYOID 1563
#define XK_PG_SYSDICT_NUMERICARRAYOID 1231
#define XK_PG_SYSDICT_REFCURSORARRAYOID 2201
#define XK_PG_SYSDICT_REGPROCEDUREARRAYOID 2207
#define XK_PG_SYSDICT_REGOPERARRAYOID 2208
#define XK_PG_SYSDICT_REGOPERATORARRAYOID 2209
#define XK_PG_SYSDICT_REGCLASSARRAYOID 2210
#define XK_PG_SYSDICT_REGCOLLATIONARRAYOID 4192
#define XK_PG_SYSDICT_REGTYPEARRAYOID 2211
#define XK_PG_SYSDICT_REGROLEARRAYOID 4097
#define XK_PG_SYSDICT_REGNAMESPACEARRAYOID 4090
#define XK_PG_SYSDICT_UUIDARRAYOID 2951
#define XK_PG_SYSDICT_PG_LSNARRAYOID 3221
#define XK_PG_SYSDICT_TSVECTORARRAYOID 3643
#define XK_PG_SYSDICT_GTSVECTORARRAYOID 3644
#define XK_PG_SYSDICT_TSQUERYARRAYOID 3645
#define XK_PG_SYSDICT_REGCONFIGARRAYOID 3735
#define XK_PG_SYSDICT_REGDICTIONARYARRAYOID 3770
#define XK_PG_SYSDICT_JSONBARRAYOID 3807
#define XK_PG_SYSDICT_JSONPATHARRAYOID 4073
#define XK_PG_SYSDICT_TXID_SNAPSHOTARRAYOID 2949
#define XK_PG_SYSDICT_PG_SNAPSHOTARRAYOID 5039
#define XK_PG_SYSDICT_INT4RANGEARRAYOID 3905
#define XK_PG_SYSDICT_NUMRANGEARRAYOID 3907
#define XK_PG_SYSDICT_TSRANGEARRAYOID 3909
#define XK_PG_SYSDICT_TSTZRANGEARRAYOID 3911
#define XK_PG_SYSDICT_DATERANGEARRAYOID 3913
#define XK_PG_SYSDICT_INT8RANGEARRAYOID 3927
#define XK_PG_SYSDICT_INT4MULTIRANGEARRAYOID 6150
#define XK_PG_SYSDICT_NUMMULTIRANGEARRAYOID 6151
#define XK_PG_SYSDICT_TSMULTIRANGEARRAYOID 6152
#define XK_PG_SYSDICT_TSTZMULTIRANGEARRAYOID 6153
#define XK_PG_SYSDICT_DATEMULTIRANGEARRAYOID 6155
#define XK_PG_SYSDICT_INT8MULTIRANGEARRAYOID 6157
#define XK_PG_SYSDICT_CSTRINGARRAYOID 1263

#elif XK_PG_VERSION_NUM >= 140000 && XK_PG_VERSION_NUM < 150000
#define XK_PG_SYSDICT_CASHOID   XK_PG_SYSDICT_MONEYOID
#define XK_PG_SYSDICT_LSNOID    XK_PG_SYSDICT_PG_LSNOID

#define XK_PG_SYSDICT_BOOLOID 16
#define XK_PG_SYSDICT_BYTEAOID 17
#define XK_PG_SYSDICT_CHAROID 18
#define XK_PG_SYSDICT_NAMEOID 19
#define XK_PG_SYSDICT_INT8OID 20
#define XK_PG_SYSDICT_INT2OID 21
#define XK_PG_SYSDICT_INT2VECTOROID 22
#define XK_PG_SYSDICT_INT4OID 23
#define XK_PG_SYSDICT_REGPROCOID 24
#define XK_PG_SYSDICT_TEXTOID 25
#define XK_PG_SYSDICT_OIDOID 26
#define XK_PG_SYSDICT_TIDOID 27
#define XK_PG_SYSDICT_XIDOID 28
#define XK_PG_SYSDICT_CIDOID 29
#define XK_PG_SYSDICT_OIDVECTOROID 30
#define XK_PG_SYSDICT_JSONOID 114
#define XK_PG_SYSDICT_XMLOID 142
#define XK_PG_SYSDICT_PG_NODE_TREEOID 194
#define XK_PG_SYSDICT_PG_NDISTINCTOID 3361
#define XK_PG_SYSDICT_PG_DEPENDENCIESOID 3402
#define XK_PG_SYSDICT_PG_MCV_LISTOID 5017
#define XK_PG_SYSDICT_PG_DDL_COMMANDOID 32
#define XK_PG_SYSDICT_XID8OID 5069
#define XK_PG_SYSDICT_POINTOID 600
#define XK_PG_SYSDICT_LSEGOID 601
#define XK_PG_SYSDICT_PATHOID 602
#define XK_PG_SYSDICT_BOXOID 603
#define XK_PG_SYSDICT_POLYGONOID 604
#define XK_PG_SYSDICT_LINEOID 628
#define XK_PG_SYSDICT_FLOAT4OID 700
#define XK_PG_SYSDICT_FLOAT8OID 701
#define XK_PG_SYSDICT_UNKNOWNOID 705
#define XK_PG_SYSDICT_CIRCLEOID 718
#define XK_PG_SYSDICT_MONEYOID 790
#define XK_PG_SYSDICT_MACADDROID 829
#define XK_PG_SYSDICT_INETOID 869
#define XK_PG_SYSDICT_CIDROID 650
#define XK_PG_SYSDICT_MACADDR8OID 774
#define XK_PG_SYSDICT_ACLITEMOID 1033
#define XK_PG_SYSDICT_BPCHAROID 1042
#define XK_PG_SYSDICT_VARCHAROID 1043
#define XK_PG_SYSDICT_DATEOID 1082
#define XK_PG_SYSDICT_TIMEOID 1083
#define XK_PG_SYSDICT_TIMESTAMPOID 1114
#define XK_PG_SYSDICT_TIMESTAMPTZOID 1184
#define XK_PG_SYSDICT_INTERVALOID 1186
#define XK_PG_SYSDICT_TIMETZOID 1266
#define XK_PG_SYSDICT_BITOID 1560
#define XK_PG_SYSDICT_VARBITOID 1562
#define XK_PG_SYSDICT_NUMERICOID 1700
#define XK_PG_SYSDICT_REFCURSOROID 1790
#define XK_PG_SYSDICT_REGPROCEDUREOID 2202
#define XK_PG_SYSDICT_REGOPEROID 2203
#define XK_PG_SYSDICT_REGOPERATOROID 2204
#define XK_PG_SYSDICT_REGCLASSOID 2205
#define XK_PG_SYSDICT_REGCOLLATIONOID 4191
#define XK_PG_SYSDICT_REGTYPEOID 2206
#define XK_PG_SYSDICT_REGROLEOID 4096
#define XK_PG_SYSDICT_REGNAMESPACEOID 4089
#define XK_PG_SYSDICT_UUIDOID 2950
#define XK_PG_SYSDICT_PG_LSNOID 3220
#define XK_PG_SYSDICT_TSVECTOROID 3614
#define XK_PG_SYSDICT_GTSVECTOROID 3642
#define XK_PG_SYSDICT_TSQUERYOID 3615
#define XK_PG_SYSDICT_REGCONFIGOID 3734
#define XK_PG_SYSDICT_REGDICTIONARYOID 3769
#define XK_PG_SYSDICT_JSONBOID 3802
#define XK_PG_SYSDICT_JSONPATHOID 4072
#define XK_PG_SYSDICT_TXID_SNAPSHOTOID 2970
#define XK_PG_SYSDICT_PG_SNAPSHOTOID 5038
#define XK_PG_SYSDICT_INT4RANGEOID 3904
#define XK_PG_SYSDICT_NUMRANGEOID 3906
#define XK_PG_SYSDICT_TSRANGEOID 3908
#define XK_PG_SYSDICT_TSTZRANGEOID 3910
#define XK_PG_SYSDICT_DATERANGEOID 3912
#define XK_PG_SYSDICT_INT8RANGEOID 3926
#define XK_PG_SYSDICT_INT4MULTIRANGEOID 4451
#define XK_PG_SYSDICT_NUMMULTIRANGEOID 4532
#define XK_PG_SYSDICT_TSMULTIRANGEOID 4533
#define XK_PG_SYSDICT_TSTZMULTIRANGEOID 4534
#define XK_PG_SYSDICT_DATEMULTIRANGEOID 4535
#define XK_PG_SYSDICT_INT8MULTIRANGEOID 4536
#define XK_PG_SYSDICT_RECORDOID 2249
#define XK_PG_SYSDICT_RECORDARRAYOID 2287
#define XK_PG_SYSDICT_CSTRINGOID 2275
#define XK_PG_SYSDICT_ANYOID 2276
#define XK_PG_SYSDICT_ANYARRAYOID 2277
#define XK_PG_SYSDICT_VOIDOID 2278
#define XK_PG_SYSDICT_TRIGGEROID 2279
#define XK_PG_SYSDICT_EVENT_TRIGGEROID 3838
#define XK_PG_SYSDICT_LANGUAGE_HANDLEROID 2280
#define XK_PG_SYSDICT_INTERNALOID 2281
#define XK_PG_SYSDICT_ANYELEMENTOID 2283
#define XK_PG_SYSDICT_ANYNONARRAYOID 2776
#define XK_PG_SYSDICT_ANYENUMOID 3500
#define XK_PG_SYSDICT_FDW_HANDLEROID 3115
#define XK_PG_SYSDICT_INDEX_AM_HANDLEROID 325
#define XK_PG_SYSDICT_TSM_HANDLEROID 3310
#define XK_PG_SYSDICT_TABLE_AM_HANDLEROID 269
#define XK_PG_SYSDICT_ANYRANGEOID 3831
#define XK_PG_SYSDICT_ANYCOMPATIBLEOID 5077
#define XK_PG_SYSDICT_ANYCOMPATIBLEARRAYOID 5078
#define XK_PG_SYSDICT_ANYCOMPATIBLENONARRAYOID 5079
#define XK_PG_SYSDICT_ANYCOMPATIBLERANGEOID 5080
#define XK_PG_SYSDICT_ANYMULTIRANGEOID 4537
#define XK_PG_SYSDICT_ANYCOMPATIBLEMULTIRANGEOID 4538
#define XK_PG_SYSDICT_PG_BRIN_BLOOM_SUMMARYOID 4600
#define XK_PG_SYSDICT_PG_BRIN_MINMAX_MULTI_SUMMARYOID 4601
#define XK_PG_SYSDICT_BOOLARRAYOID 1000
#define XK_PG_SYSDICT_BYTEAARRAYOID 1001
#define XK_PG_SYSDICT_CHARARRAYOID 1002
#define XK_PG_SYSDICT_NAMEARRAYOID 1003
#define XK_PG_SYSDICT_INT8ARRAYOID 1016
#define XK_PG_SYSDICT_INT2ARRAYOID 1005
#define XK_PG_SYSDICT_INT2VECTORARRAYOID 1006
#define XK_PG_SYSDICT_INT4ARRAYOID 1007
#define XK_PG_SYSDICT_REGPROCARRAYOID 1008
#define XK_PG_SYSDICT_TEXTARRAYOID 1009
#define XK_PG_SYSDICT_OIDARRAYOID 1028
#define XK_PG_SYSDICT_TIDARRAYOID 1010
#define XK_PG_SYSDICT_XIDARRAYOID 1011
#define XK_PG_SYSDICT_CIDARRAYOID 1012
#define XK_PG_SYSDICT_OIDVECTORARRAYOID 1013
#define XK_PG_SYSDICT_PG_TYPEARRAYOID 210
#define XK_PG_SYSDICT_PG_ATTRIBUTEARRAYOID 270
#define XK_PG_SYSDICT_PG_PROCARRAYOID 272
#define XK_PG_SYSDICT_PG_CLASSARRAYOID 273
#define XK_PG_SYSDICT_JSONARRAYOID 199
#define XK_PG_SYSDICT_XMLARRAYOID 143
#define XK_PG_SYSDICT_XID8ARRAYOID 271
#define XK_PG_SYSDICT_POINTARRAYOID 1017
#define XK_PG_SYSDICT_LSEGARRAYOID 1018
#define XK_PG_SYSDICT_PATHARRAYOID 1019
#define XK_PG_SYSDICT_BOXARRAYOID 1020
#define XK_PG_SYSDICT_POLYGONARRAYOID 1027
#define XK_PG_SYSDICT_LINEARRAYOID 629
#define XK_PG_SYSDICT_FLOAT4ARRAYOID 1021
#define XK_PG_SYSDICT_FLOAT8ARRAYOID 1022
#define XK_PG_SYSDICT_CIRCLEARRAYOID 719
#define XK_PG_SYSDICT_MONEYARRAYOID 791
#define XK_PG_SYSDICT_MACADDRARRAYOID 1040
#define XK_PG_SYSDICT_INETARRAYOID 1041
#define XK_PG_SYSDICT_CIDRARRAYOID 651
#define XK_PG_SYSDICT_MACADDR8ARRAYOID 775
#define XK_PG_SYSDICT_ACLITEMARRAYOID 1034
#define XK_PG_SYSDICT_BPCHARARRAYOID 1014
#define XK_PG_SYSDICT_VARCHARARRAYOID 1015
#define XK_PG_SYSDICT_DATEARRAYOID 1182
#define XK_PG_SYSDICT_TIMEARRAYOID 1183
#define XK_PG_SYSDICT_TIMESTAMPARRAYOID 1115
#define XK_PG_SYSDICT_TIMESTAMPTZARRAYOID 1185
#define XK_PG_SYSDICT_INTERVALARRAYOID 1187
#define XK_PG_SYSDICT_TIMETZARRAYOID 1270
#define XK_PG_SYSDICT_BITARRAYOID 1561
#define XK_PG_SYSDICT_VARBITARRAYOID 1563
#define XK_PG_SYSDICT_NUMERICARRAYOID 1231
#define XK_PG_SYSDICT_REFCURSORARRAYOID 2201
#define XK_PG_SYSDICT_REGPROCEDUREARRAYOID 2207
#define XK_PG_SYSDICT_REGOPERARRAYOID 2208
#define XK_PG_SYSDICT_REGOPERATORARRAYOID 2209
#define XK_PG_SYSDICT_REGCLASSARRAYOID 2210
#define XK_PG_SYSDICT_REGCOLLATIONARRAYOID 4192
#define XK_PG_SYSDICT_REGTYPEARRAYOID 2211
#define XK_PG_SYSDICT_REGROLEARRAYOID 4097
#define XK_PG_SYSDICT_REGNAMESPACEARRAYOID 4090
#define XK_PG_SYSDICT_UUIDARRAYOID 2951
#define XK_PG_SYSDICT_PG_LSNARRAYOID 3221
#define XK_PG_SYSDICT_TSVECTORARRAYOID 3643
#define XK_PG_SYSDICT_GTSVECTORARRAYOID 3644
#define XK_PG_SYSDICT_TSQUERYARRAYOID 3645
#define XK_PG_SYSDICT_REGCONFIGARRAYOID 3735
#define XK_PG_SYSDICT_REGDICTIONARYARRAYOID 3770
#define XK_PG_SYSDICT_JSONBARRAYOID 3807
#define XK_PG_SYSDICT_JSONPATHARRAYOID 4073
#define XK_PG_SYSDICT_TXID_SNAPSHOTARRAYOID 2949
#define XK_PG_SYSDICT_PG_SNAPSHOTARRAYOID 5039
#define XK_PG_SYSDICT_INT4RANGEARRAYOID 3905
#define XK_PG_SYSDICT_NUMRANGEARRAYOID 3907
#define XK_PG_SYSDICT_TSRANGEARRAYOID 3909
#define XK_PG_SYSDICT_TSTZRANGEARRAYOID 3911
#define XK_PG_SYSDICT_DATERANGEARRAYOID 3913
#define XK_PG_SYSDICT_INT8RANGEARRAYOID 3927
#define XK_PG_SYSDICT_INT4MULTIRANGEARRAYOID 6150
#define XK_PG_SYSDICT_NUMMULTIRANGEARRAYOID 6151
#define XK_PG_SYSDICT_TSMULTIRANGEARRAYOID 6152
#define XK_PG_SYSDICT_TSTZMULTIRANGEARRAYOID 6153
#define XK_PG_SYSDICT_DATEMULTIRANGEARRAYOID 6155
#define XK_PG_SYSDICT_INT8MULTIRANGEARRAYOID 6157
#define XK_PG_SYSDICT_CSTRINGARRAYOID 1263

#elif XK_PG_VERSION_NUM >= 130000 && XK_PG_VERSION_NUM < 140000
#define XK_PG_SYSDICT_BOOLOID 16
#define XK_PG_SYSDICT_BYTEAOID 17
#define XK_PG_SYSDICT_CHAROID 18
#define XK_PG_SYSDICT_NAMEOID 19
#define XK_PG_SYSDICT_INT8OID 20
#define XK_PG_SYSDICT_INT2OID 21
#define XK_PG_SYSDICT_INT2VECTOROID 22
#define XK_PG_SYSDICT_INT4OID 23
#define XK_PG_SYSDICT_REGPROCOID 24
#define XK_PG_SYSDICT_TEXTOID 25
#define XK_PG_SYSDICT_OIDOID 26
#define XK_PG_SYSDICT_TIDOID 27
#define XK_PG_SYSDICT_XIDOID 28
#define XK_PG_SYSDICT_CIDOID 29
#define XK_PG_SYSDICT_OIDVECTOROID 30
#define XK_PG_SYSDICT_JSONOID 114
#define XK_PG_SYSDICT_XMLOID 142
#define XK_PG_SYSDICT_PGNODETREEOID 194
#define XK_PG_SYSDICT_PGNDISTINCTOID 3361
#define XK_PG_SYSDICT_PGDEPENDENCIESOID 3402
#define XK_PG_SYSDICT_PGMCVLISTOID 5017
#define XK_PG_SYSDICT_PGDDLCOMMANDOID 32
#define XK_PG_SYSDICT_XID8OID 5069
#define XK_PG_SYSDICT_POINTOID 600
#define XK_PG_SYSDICT_LSEGOID 601
#define XK_PG_SYSDICT_PATHOID 602
#define XK_PG_SYSDICT_BOXOID 603
#define XK_PG_SYSDICT_POLYGONOID 604
#define XK_PG_SYSDICT_LINEOID 628
#define XK_PG_SYSDICT_FLOAT4OID 700
#define XK_PG_SYSDICT_FLOAT8OID 701
#define XK_PG_SYSDICT_UNKNOWNOID 705
#define XK_PG_SYSDICT_CIRCLEOID 718
#define XK_PG_SYSDICT_CASHOID 790
#define XK_PG_SYSDICT_MACADDROID 829
#define XK_PG_SYSDICT_INETOID 869
#define XK_PG_SYSDICT_CIDROID 650
#define XK_PG_SYSDICT_MACADDR8OID 774
#define XK_PG_SYSDICT_ACLITEMOID 1033
#define XK_PG_SYSDICT_BPCHAROID 1042
#define XK_PG_SYSDICT_VARCHAROID 1043
#define XK_PG_SYSDICT_DATEOID 1082
#define XK_PG_SYSDICT_TIMEOID 1083
#define XK_PG_SYSDICT_TIMESTAMPOID 1114
#define XK_PG_SYSDICT_TIMESTAMPTZOID 1184
#define XK_PG_SYSDICT_INTERVALOID 1186
#define XK_PG_SYSDICT_TIMETZOID 1266
#define XK_PG_SYSDICT_BITOID 1560
#define XK_PG_SYSDICT_VARBITOID 1562
#define XK_PG_SYSDICT_NUMERICOID 1700
#define XK_PG_SYSDICT_REFCURSOROID 1790
#define XK_PG_SYSDICT_REGPROCEDUREOID 2202
#define XK_PG_SYSDICT_REGOPEROID 2203
#define XK_PG_SYSDICT_REGOPERATOROID 2204
#define XK_PG_SYSDICT_REGCLASSOID 2205
#define XK_PG_SYSDICT_REGCOLLATIONOID 4191
#define XK_PG_SYSDICT_REGTYPEOID 2206
#define XK_PG_SYSDICT_REGROLEOID 4096
#define XK_PG_SYSDICT_REGNAMESPACEOID 4089
#define XK_PG_SYSDICT_UUIDOID 2950
#define XK_PG_SYSDICT_LSNOID 3220
#define XK_PG_SYSDICT_TSVECTOROID 3614
#define XK_PG_SYSDICT_GTSVECTOROID 3642
#define XK_PG_SYSDICT_TSQUERYOID 3615
#define XK_PG_SYSDICT_REGCONFIGOID 3734
#define XK_PG_SYSDICT_REGDICTIONARYOID 3769
#define XK_PG_SYSDICT_JSONBOID 3802
#define XK_PG_SYSDICT_JSONPATHOID 4072
#define XK_PG_SYSDICT_TXID_SNAPSHOTOID 2970
#define XK_PG_SYSDICT_PG_SNAPSHOTOID 5038
#define XK_PG_SYSDICT_INT4RANGEOID 3904
#define XK_PG_SYSDICT_NUMRANGEOID 3906
#define XK_PG_SYSDICT_TSRANGEOID 3908
#define XK_PG_SYSDICT_TSTZRANGEOID 3910
#define XK_PG_SYSDICT_DATERANGEOID 3912
#define XK_PG_SYSDICT_INT8RANGEOID 3926
#define XK_PG_SYSDICT_RECORDOID 2249
#define XK_PG_SYSDICT_RECORDARRAYOID 2287
#define XK_PG_SYSDICT_CSTRINGOID 2275
#define XK_PG_SYSDICT_ANYOID 2276
#define XK_PG_SYSDICT_ANYARRAYOID 2277
#define XK_PG_SYSDICT_VOIDOID 2278
#define XK_PG_SYSDICT_TRIGGEROID 2279
#define XK_PG_SYSDICT_EVTTRIGGEROID 3838
#define XK_PG_SYSDICT_LANGUAGE_HANDLEROID 2280
#define XK_PG_SYSDICT_INTERNALOID 2281
#define XK_PG_SYSDICT_ANYELEMENTOID 2283
#define XK_PG_SYSDICT_ANYNONARRAYOID 2776
#define XK_PG_SYSDICT_ANYENUMOID 3500
#define XK_PG_SYSDICT_FDW_HANDLEROID 3115
#define XK_PG_SYSDICT_INDEX_AM_HANDLEROID 325
#define XK_PG_SYSDICT_TSM_HANDLEROID 3310
#define XK_PG_SYSDICT_TABLE_AM_HANDLEROID 269
#define XK_PG_SYSDICT_ANYRANGEOID 3831
#define XK_PG_SYSDICT_ANYCOMPATIBLEOID 5077
#define XK_PG_SYSDICT_ANYCOMPATIBLEARRAYOID 5078
#define XK_PG_SYSDICT_ANYCOMPATIBLENONARRAYOID 5079
#define XK_PG_SYSDICT_ANYCOMPATIBLERANGEOID 5080
#define XK_PG_SYSDICT_BOOLARRAYOID 1000
#define XK_PG_SYSDICT_BYTEAARRAYOID 1001
#define XK_PG_SYSDICT_CHARARRAYOID 1002
#define XK_PG_SYSDICT_NAMEARRAYOID 1003
#define XK_PG_SYSDICT_INT8ARRAYOID 1016
#define XK_PG_SYSDICT_INT2ARRAYOID 1005
#define XK_PG_SYSDICT_INT2VECTORARRAYOID 1006
#define XK_PG_SYSDICT_INT4ARRAYOID 1007
#define XK_PG_SYSDICT_REGPROCARRAYOID 1008
#define XK_PG_SYSDICT_TEXTARRAYOID 1009
#define XK_PG_SYSDICT_OIDARRAYOID 1028
#define XK_PG_SYSDICT_TIDARRAYOID 1010
#define XK_PG_SYSDICT_XIDARRAYOID 1011
#define XK_PG_SYSDICT_CIDARRAYOID 1012
#define XK_PG_SYSDICT_OIDVECTORARRAYOID 1013
#define XK_PG_SYSDICT_JSONARRAYOID 199
#define XK_PG_SYSDICT_XMLARRAYOID 143
#define XK_PG_SYSDICT_XID8ARRAYOID 271
#define XK_PG_SYSDICT_POINTARRAYOID 1017
#define XK_PG_SYSDICT_LSEGARRAYOID 1018
#define XK_PG_SYSDICT_PATHARRAYOID 1019
#define XK_PG_SYSDICT_BOXARRAYOID 1020
#define XK_PG_SYSDICT_POLYGONARRAYOID 1027
#define XK_PG_SYSDICT_LINEARRAYOID 629
#define XK_PG_SYSDICT_FLOAT4ARRAYOID 1021
#define XK_PG_SYSDICT_FLOAT8ARRAYOID 1022
#define XK_PG_SYSDICT_CIRCLEARRAYOID 719
#define XK_PG_SYSDICT_MONEYARRAYOID 791
#define XK_PG_SYSDICT_MACADDRARRAYOID 1040
#define XK_PG_SYSDICT_INETARRAYOID 1041
#define XK_PG_SYSDICT_CIDRARRAYOID 651
#define XK_PG_SYSDICT_MACADDR8ARRAYOID 775
#define XK_PG_SYSDICT_ACLITEMARRAYOID 1034
#define XK_PG_SYSDICT_BPCHARARRAYOID 1014
#define XK_PG_SYSDICT_VARCHARARRAYOID 1015
#define XK_PG_SYSDICT_DATEARRAYOID 1182
#define XK_PG_SYSDICT_TIMEARRAYOID 1183
#define XK_PG_SYSDICT_TIMESTAMPARRAYOID 1115
#define XK_PG_SYSDICT_TIMESTAMPTZARRAYOID 1185
#define XK_PG_SYSDICT_INTERVALARRAYOID 1187
#define XK_PG_SYSDICT_TIMETZARRAYOID 1270
#define XK_PG_SYSDICT_BITARRAYOID 1561
#define XK_PG_SYSDICT_VARBITARRAYOID 1563
#define XK_PG_SYSDICT_NUMERICARRAYOID 1231
#define XK_PG_SYSDICT_REFCURSORARRAYOID 2201
#define XK_PG_SYSDICT_REGPROCEDUREARRAYOID 2207
#define XK_PG_SYSDICT_REGOPERARRAYOID 2208
#define XK_PG_SYSDICT_REGOPERATORARRAYOID 2209
#define XK_PG_SYSDICT_REGCLASSARRAYOID 2210
#define XK_PG_SYSDICT_REGCOLLATIONARRAYOID 4192
#define XK_PG_SYSDICT_REGTYPEARRAYOID 2211
#define XK_PG_SYSDICT_REGROLEARRAYOID 4097
#define XK_PG_SYSDICT_REGNAMESPACEARRAYOID 4090
#define XK_PG_SYSDICT_UUIDARRAYOID 2951
#define XK_PG_SYSDICT_PG_LSNARRAYOID 3221
#define XK_PG_SYSDICT_TSVECTORARRAYOID 3643
#define XK_PG_SYSDICT_GTSVECTORARRAYOID 3644
#define XK_PG_SYSDICT_TSQUERYARRAYOID 3645
#define XK_PG_SYSDICT_REGCONFIGARRAYOID 3735
#define XK_PG_SYSDICT_REGDICTIONARYARRAYOID 3770
#define XK_PG_SYSDICT_JSONBARRAYOID 3807
#define XK_PG_SYSDICT_JSONPATHARRAYOID 4073
#define XK_PG_SYSDICT_TXID_SNAPSHOTARRAYOID 2949
#define XK_PG_SYSDICT_PG_SNAPSHOTARRAYOID 5039
#define XK_PG_SYSDICT_INT4RANGEARRAYOID 3905
#define XK_PG_SYSDICT_NUMRANGEARRAYOID 3907
#define XK_PG_SYSDICT_TSRANGEARRAYOID 3909
#define XK_PG_SYSDICT_TSTZRANGEARRAYOID 3911
#define XK_PG_SYSDICT_DATERANGEARRAYOID 3913
#define XK_PG_SYSDICT_INT8RANGEARRAYOID 3927
#define XK_PG_SYSDICT_CSTRINGARRAYOID 1263

#elif XK_PG_VERSION_NUM >= 120000 && XK_PG_VERSION_NUM < 130000
#define XK_PG_SYSDICT_BOOLOID 16
#define XK_PG_SYSDICT_BYTEAOID 17
#define XK_PG_SYSDICT_CHAROID 18
#define XK_PG_SYSDICT_NAMEOID 19
#define XK_PG_SYSDICT_INT8OID 20
#define XK_PG_SYSDICT_INT2OID 21
#define XK_PG_SYSDICT_INT2VECTOROID 22
#define XK_PG_SYSDICT_INT4OID 23
#define XK_PG_SYSDICT_REGPROCOID 24
#define XK_PG_SYSDICT_TEXTOID 25
#define XK_PG_SYSDICT_OIDOID 26
#define XK_PG_SYSDICT_TIDOID 27
#define XK_PG_SYSDICT_XIDOID 28
#define XK_PG_SYSDICT_CIDOID 29
#define XK_PG_SYSDICT_OIDVECTOROID 30
#define XK_PG_SYSDICT_JSONOID 114
#define XK_PG_SYSDICT_XMLOID 142
#define XK_PG_SYSDICT_PGNODETREEOID 194
#define XK_PG_SYSDICT_PGNDISTINCTOID 3361
#define XK_PG_SYSDICT_PGDEPENDENCIESOID 3402
#define XK_PG_SYSDICT_PGMCVLISTOID 5017
#define XK_PG_SYSDICT_PGDDLCOMMANDOID 32
#define XK_PG_SYSDICT_POINTOID 600
#define XK_PG_SYSDICT_LSEGOID 601
#define XK_PG_SYSDICT_PATHOID 602
#define XK_PG_SYSDICT_BOXOID 603
#define XK_PG_SYSDICT_POLYGONOID 604
#define XK_PG_SYSDICT_LINEOID 628
#define XK_PG_SYSDICT_FLOAT4OID 700
#define XK_PG_SYSDICT_FLOAT8OID 701
#define XK_PG_SYSDICT_UNKNOWNOID 705
#define XK_PG_SYSDICT_CIRCLEOID 718
#define XK_PG_SYSDICT_CASHOID 790
#define XK_PG_SYSDICT_MACADDROID 829
#define XK_PG_SYSDICT_INETOID 869
#define XK_PG_SYSDICT_CIDROID 650
#define XK_PG_SYSDICT_MACADDR8OID 774
#define XK_PG_SYSDICT_ACLITEMOID 1033
#define XK_PG_SYSDICT_BPCHAROID 1042
#define XK_PG_SYSDICT_VARCHAROID 1043
#define XK_PG_SYSDICT_DATEOID 1082
#define XK_PG_SYSDICT_TIMEOID 1083
#define XK_PG_SYSDICT_TIMESTAMPOID 1114
#define XK_PG_SYSDICT_TIMESTAMPTZOID 1184
#define XK_PG_SYSDICT_INTERVALOID 1186
#define XK_PG_SYSDICT_TIMETZOID 1266
#define XK_PG_SYSDICT_BITOID 1560
#define XK_PG_SYSDICT_VARBITOID 1562
#define XK_PG_SYSDICT_NUMERICOID 1700
#define XK_PG_SYSDICT_REFCURSOROID 1790
#define XK_PG_SYSDICT_REGPROCEDUREOID 2202
#define XK_PG_SYSDICT_REGOPEROID 2203
#define XK_PG_SYSDICT_REGOPERATOROID 2204
#define XK_PG_SYSDICT_REGCLASSOID 2205
#define XK_PG_SYSDICT_REGTYPEOID 2206
#define XK_PG_SYSDICT_REGROLEOID 4096
#define XK_PG_SYSDICT_REGNAMESPACEOID 4089
#define XK_PG_SYSDICT_UUIDOID 2950
#define XK_PG_SYSDICT_LSNOID 3220
#define XK_PG_SYSDICT_TSVECTOROID 3614
#define XK_PG_SYSDICT_GTSVECTOROID 3642
#define XK_PG_SYSDICT_TSQUERYOID 3615
#define XK_PG_SYSDICT_REGCONFIGOID 3734
#define XK_PG_SYSDICT_REGDICTIONARYOID 3769
#define XK_PG_SYSDICT_JSONBOID 3802
#define XK_PG_SYSDICT_JSONPATHOID 4072
#define XK_PG_SYSDICT_TXID_SNAPSHOTOID 2970
#define XK_PG_SYSDICT_INT4RANGEOID 3904
#define XK_PG_SYSDICT_NUMRANGEOID 3906
#define XK_PG_SYSDICT_TSRANGEOID 3908
#define XK_PG_SYSDICT_TSTZRANGEOID 3910
#define XK_PG_SYSDICT_DATERANGEOID 3912
#define XK_PG_SYSDICT_INT8RANGEOID 3926
#define XK_PG_SYSDICT_RECORDOID 2249
#define XK_PG_SYSDICT_RECORDARRAYOID 2287
#define XK_PG_SYSDICT_CSTRINGOID 2275
#define XK_PG_SYSDICT_ANYOID 2276
#define XK_PG_SYSDICT_ANYARRAYOID 2277
#define XK_PG_SYSDICT_VOIDOID 2278
#define XK_PG_SYSDICT_TRIGGEROID 2279
#define XK_PG_SYSDICT_EVTTRIGGEROID 3838
#define XK_PG_SYSDICT_LANGUAGE_HANDLEROID 2280
#define XK_PG_SYSDICT_INTERNALOID 2281
#define XK_PG_SYSDICT_OPAQUEOID 2282
#define XK_PG_SYSDICT_ANYELEMENTOID 2283
#define XK_PG_SYSDICT_ANYNONARRAYOID 2776
#define XK_PG_SYSDICT_ANYENUMOID 3500
#define XK_PG_SYSDICT_FDW_HANDLEROID 3115
#define XK_PG_SYSDICT_INDEX_AM_HANDLEROID 325
#define XK_PG_SYSDICT_TSM_HANDLEROID 3310
#define XK_PG_SYSDICT_TABLE_AM_HANDLEROID 269
#define XK_PG_SYSDICT_ANYRANGEOID 3831
#define XK_PG_SYSDICT_BOOLARRAYOID 1000
#define XK_PG_SYSDICT_BYTEAARRAYOID 1001
#define XK_PG_SYSDICT_CHARARRAYOID 1002
#define XK_PG_SYSDICT_NAMEARRAYOID 1003
#define XK_PG_SYSDICT_INT8ARRAYOID 1016
#define XK_PG_SYSDICT_INT2ARRAYOID 1005
#define XK_PG_SYSDICT_INT2VECTORARRAYOID 1006
#define XK_PG_SYSDICT_INT4ARRAYOID 1007
#define XK_PG_SYSDICT_REGPROCARRAYOID 1008
#define XK_PG_SYSDICT_TEXTARRAYOID 1009
#define XK_PG_SYSDICT_OIDARRAYOID 1028
#define XK_PG_SYSDICT_TIDARRAYOID 1010
#define XK_PG_SYSDICT_XIDARRAYOID 1011
#define XK_PG_SYSDICT_CIDARRAYOID 1012
#define XK_PG_SYSDICT_OIDVECTORARRAYOID 1013
#define XK_PG_SYSDICT_JSONARRAYOID 199
#define XK_PG_SYSDICT_XMLARRAYOID 143
#define XK_PG_SYSDICT_POINTARRAYOID 1017
#define XK_PG_SYSDICT_LSEGARRAYOID 1018
#define XK_PG_SYSDICT_PATHARRAYOID 1019
#define XK_PG_SYSDICT_BOXARRAYOID 1020
#define XK_PG_SYSDICT_POLYGONARRAYOID 1027
#define XK_PG_SYSDICT_LINEARRAYOID 629
#define XK_PG_SYSDICT_FLOAT4ARRAYOID 1021
#define XK_PG_SYSDICT_FLOAT8ARRAYOID 1022
#define XK_PG_SYSDICT_CIRCLEARRAYOID 719
#define XK_PG_SYSDICT_MONEYARRAYOID 791
#define XK_PG_SYSDICT_MACADDRARRAYOID 1040
#define XK_PG_SYSDICT_INETARRAYOID 1041
#define XK_PG_SYSDICT_CIDRARRAYOID 651
#define XK_PG_SYSDICT_MACADDR8ARRAYOID 775
#define XK_PG_SYSDICT_ACLITEMARRAYOID 1034
#define XK_PG_SYSDICT_BPCHARARRAYOID 1014
#define XK_PG_SYSDICT_VARCHARARRAYOID 1015
#define XK_PG_SYSDICT_DATEARRAYOID 1182
#define XK_PG_SYSDICT_TIMEARRAYOID 1183
#define XK_PG_SYSDICT_TIMESTAMPARRAYOID 1115
#define XK_PG_SYSDICT_TIMESTAMPTZARRAYOID 1185
#define XK_PG_SYSDICT_INTERVALARRAYOID 1187
#define XK_PG_SYSDICT_TIMETZARRAYOID 1270
#define XK_PG_SYSDICT_BITARRAYOID 1561
#define XK_PG_SYSDICT_VARBITARRAYOID 1563
#define XK_PG_SYSDICT_NUMERICARRAYOID 1231
#define XK_PG_SYSDICT_REFCURSORARRAYOID 2201
#define XK_PG_SYSDICT_REGPROCEDUREARRAYOID 2207
#define XK_PG_SYSDICT_REGOPERARRAYOID 2208
#define XK_PG_SYSDICT_REGOPERATORARRAYOID 2209
#define XK_PG_SYSDICT_REGCLASSARRAYOID 2210
#define XK_PG_SYSDICT_REGTYPEARRAYOID 2211
#define XK_PG_SYSDICT_REGROLEARRAYOID 4097
#define XK_PG_SYSDICT_REGNAMESPACEARRAYOID 4090
#define XK_PG_SYSDICT_UUIDARRAYOID 2951
#define XK_PG_SYSDICT_PG_LSNARRAYOID 3221
#define XK_PG_SYSDICT_TSVECTORARRAYOID 3643
#define XK_PG_SYSDICT_GTSVECTORARRAYOID 3644
#define XK_PG_SYSDICT_TSQUERYARRAYOID 3645
#define XK_PG_SYSDICT_REGCONFIGARRAYOID 3735
#define XK_PG_SYSDICT_REGDICTIONARYARRAYOID 3770
#define XK_PG_SYSDICT_JSONBARRAYOID 3807
#define XK_PG_SYSDICT_JSONPATHARRAYOID 4073
#define XK_PG_SYSDICT_TXID_SNAPSHOTARRAYOID 2949
#define XK_PG_SYSDICT_INT4RANGEARRAYOID 3905
#define XK_PG_SYSDICT_NUMRANGEARRAYOID 3907
#define XK_PG_SYSDICT_TSRANGEARRAYOID 3909
#define XK_PG_SYSDICT_TSTZRANGEARRAYOID 3911
#define XK_PG_SYSDICT_DATERANGEARRAYOID 3913
#define XK_PG_SYSDICT_INT8RANGEARRAYOID 3927
#define XK_PG_SYSDICT_CSTRINGARRAYOID 1263

#elif XK_PG_VERSION_NUM >= 110000 && XK_PG_VERSION_NUM < 120000
#define XK_PG_SYSDICT_BOOLOID 16
#define XK_PG_SYSDICT_BYTEAOID 17
#define XK_PG_SYSDICT_CHAROID 18
#define XK_PG_SYSDICT_NAMEOID 19
#define XK_PG_SYSDICT_INT8OID 20
#define XK_PG_SYSDICT_INT2OID 21
#define XK_PG_SYSDICT_INT2VECTOROID 22
#define XK_PG_SYSDICT_INT4OID 23
#define XK_PG_SYSDICT_REGPROCOID 24
#define XK_PG_SYSDICT_TEXTOID 25
#define XK_PG_SYSDICT_OIDOID 26
#define XK_PG_SYSDICT_TIDOID 27
#define XK_PG_SYSDICT_XIDOID 28
#define XK_PG_SYSDICT_CIDOID 29
#define XK_PG_SYSDICT_OIDVECTOROID 30
#define XK_PG_SYSDICT_JSONOID 114
#define XK_PG_SYSDICT_XMLOID 142
#define XK_PG_SYSDICT_XMLARRAYOID 143
#define XK_PG_SYSDICT_JSONARRAYOID 199
#define XK_PG_SYSDICT_PGNODETREEOID 194
#define XK_PG_SYSDICT_PGNDISTINCTOID 3361
#define XK_PG_SYSDICT_PGDEPENDENCIESOID 3402
#define XK_PG_SYSDICT_PGDDLCOMMANDOID 32
#define XK_PG_SYSDICT_SMGROID 210
#define XK_PG_SYSDICT_POINTOID 600
#define XK_PG_SYSDICT_LSEGOID 601
#define XK_PG_SYSDICT_PATHOID 602
#define XK_PG_SYSDICT_BOXOID 603
#define XK_PG_SYSDICT_POLYGONOID 604
#define XK_PG_SYSDICT_LINEOID 628
#define XK_PG_SYSDICT_LINEARRAYOID 629
#define XK_PG_SYSDICT_FLOAT4OID 700
#define XK_PG_SYSDICT_FLOAT8OID 701
#define XK_PG_SYSDICT_ABSTIMEOID 702
#define XK_PG_SYSDICT_RELTIMEOID 703
#define XK_PG_SYSDICT_TINTERVALOID 704
#define XK_PG_SYSDICT_UNKNOWNOID 705
#define XK_PG_SYSDICT_CIRCLEOID 718
#define XK_PG_SYSDICT_CIRCLEARRAYOID 719
#define XK_PG_SYSDICT_CASHOID 790
#define XK_PG_SYSDICT_MONEYARRAYOID 791
#define XK_PG_SYSDICT_MACADDROID 829
#define XK_PG_SYSDICT_INETOID 869
#define XK_PG_SYSDICT_CIDROID 650
#define XK_PG_SYSDICT_MACADDR8OID 774
#define XK_PG_SYSDICT_BOOLARRAYOID 1000
#define XK_PG_SYSDICT_BYTEAARRAYOID 1001
#define XK_PG_SYSDICT_CHARARRAYOID 1002
#define XK_PG_SYSDICT_NAMEARRAYOID 1003
#define XK_PG_SYSDICT_INT2ARRAYOID 1005
#define XK_PG_SYSDICT_INT2VECTORARRAYOID 1006
#define XK_PG_SYSDICT_INT4ARRAYOID 1007
#define XK_PG_SYSDICT_REGPROCARRAYOID 1008
#define XK_PG_SYSDICT_TEXTARRAYOID 1009
#define XK_PG_SYSDICT_OIDARRAYOID 1028
#define XK_PG_SYSDICT_TIDARRAYOID 1010
#define XK_PG_SYSDICT_XIDARRAYOID 1011
#define XK_PG_SYSDICT_CIDARRAYOID 1012
#define XK_PG_SYSDICT_OIDVECTORARRAYOID 1013
#define XK_PG_SYSDICT_BPCHARARRAYOID 1014
#define XK_PG_SYSDICT_VARCHARARRAYOID 1015
#define XK_PG_SYSDICT_INT8ARRAYOID 1016
#define XK_PG_SYSDICT_POINTARRAYOID 1017
#define XK_PG_SYSDICT_LSEGARRAYOID 1018
#define XK_PG_SYSDICT_PATHARRAYOID 1019
#define XK_PG_SYSDICT_BOXARRAYOID 1020
#define XK_PG_SYSDICT_FLOAT4ARRAYOID 1021
#define XK_PG_SYSDICT_FLOAT8ARRAYOID 1022
#define XK_PG_SYSDICT_ABSTIMEARRAYOID 1023
#define XK_PG_SYSDICT_RELTIMEARRAYOID 1024
#define XK_PG_SYSDICT_TINTERVALARRAYOID 1025
#define XK_PG_SYSDICT_POLYGONARRAYOID 1027
#define XK_PG_SYSDICT_ACLITEMOID 1033
#define XK_PG_SYSDICT_ACLITEMARRAYOID 1034
#define XK_PG_SYSDICT_MACADDRARRAYOID 1040
#define XK_PG_SYSDICT_MACADDR8ARRAYOID 775
#define XK_PG_SYSDICT_INETARRAYOID 1041
#define XK_PG_SYSDICT_CIDRARRAYOID 651
#define XK_PG_SYSDICT_CSTRINGARRAYOID 1263
#define XK_PG_SYSDICT_BPCHAROID 1042
#define XK_PG_SYSDICT_VARCHAROID 1043
#define XK_PG_SYSDICT_DATEOID 1082
#define XK_PG_SYSDICT_TIMEOID 1083
#define XK_PG_SYSDICT_TIMESTAMPOID 1114
#define XK_PG_SYSDICT_TIMESTAMPARRAYOID 1115
#define XK_PG_SYSDICT_DATEARRAYOID 1182
#define XK_PG_SYSDICT_TIMEARRAYOID 1183
#define XK_PG_SYSDICT_TIMESTAMPTZOID 1184
#define XK_PG_SYSDICT_TIMESTAMPTZARRAYOID 1185
#define XK_PG_SYSDICT_INTERVALOID 1186
#define XK_PG_SYSDICT_INTERVALARRAYOID 1187
#define XK_PG_SYSDICT_NUMERICARRAYOID 1231
#define XK_PG_SYSDICT_TIMETZOID 1266
#define XK_PG_SYSDICT_TIMETZARRAYOID 1270
#define XK_PG_SYSDICT_BITOID 1560
#define XK_PG_SYSDICT_BITARRAYOID 1561
#define XK_PG_SYSDICT_VARBITOID 1562
#define XK_PG_SYSDICT_VARBITARRAYOID 1563
#define XK_PG_SYSDICT_NUMERICOID 1700
#define XK_PG_SYSDICT_REFCURSOROID 1790
#define XK_PG_SYSDICT_REFCURSORARRAYOID 2201
#define XK_PG_SYSDICT_REGPROCEDUREOID 2202
#define XK_PG_SYSDICT_REGOPEROID 2203
#define XK_PG_SYSDICT_REGOPERATOROID 2204
#define XK_PG_SYSDICT_REGCLASSOID 2205
#define XK_PG_SYSDICT_REGTYPEOID 2206
#define XK_PG_SYSDICT_REGROLEOID 4096
#define XK_PG_SYSDICT_REGNAMESPACEOID 4089
#define XK_PG_SYSDICT_REGPROCEDUREARRAYOID 2207
#define XK_PG_SYSDICT_REGOPERARRAYOID 2208
#define XK_PG_SYSDICT_REGOPERATORARRAYOID 2209
#define XK_PG_SYSDICT_REGCLASSARRAYOID 2210
#define XK_PG_SYSDICT_REGTYPEARRAYOID 2211
#define XK_PG_SYSDICT_REGROLEARRAYOID 4097
#define XK_PG_SYSDICT_REGNAMESPACEARRAYOID 4090
#define XK_PG_SYSDICT_UUIDOID 2950
#define XK_PG_SYSDICT_UUIDARRAYOID 2951
#define XK_PG_SYSDICT_LSNOID 3220
#define XK_PG_SYSDICT_PG_LSNARRAYOID 3221
#define XK_PG_SYSDICT_TSVECTOROID 3614
#define XK_PG_SYSDICT_GTSVECTOROID 3642
#define XK_PG_SYSDICT_TSQUERYOID 3615
#define XK_PG_SYSDICT_REGCONFIGOID 3734
#define XK_PG_SYSDICT_REGDICTIONARYOID 3769
#define XK_PG_SYSDICT_TSVECTORARRAYOID 3643
#define XK_PG_SYSDICT_GTSVECTORARRAYOID 3644
#define XK_PG_SYSDICT_TSQUERYARRAYOID 3645
#define XK_PG_SYSDICT_REGCONFIGARRAYOID 3735
#define XK_PG_SYSDICT_REGDICTIONARYARRAYOID 3770
#define XK_PG_SYSDICT_JSONBOID 3802
#define XK_PG_SYSDICT_JSONBARRAYOID 3807
#define XK_PG_SYSDICT_TXID_SNAPSHOTOID 2970
#define XK_PG_SYSDICT_TXID_SNAPSHOTARRAYOID 2949
#define XK_PG_SYSDICT_INT4RANGEOID 3904
#define XK_PG_SYSDICT_INT4RANGEARRAYOID 3905
#define XK_PG_SYSDICT_NUMRANGEOID 3906
#define XK_PG_SYSDICT_NUMRANGEARRAYOID 3907
#define XK_PG_SYSDICT_TSRANGEOID 3908
#define XK_PG_SYSDICT_TSRANGEARRAYOID 3909
#define XK_PG_SYSDICT_TSTZRANGEOID 3910
#define XK_PG_SYSDICT_TSTZRANGEARRAYOID 3911
#define XK_PG_SYSDICT_DATERANGEOID 3912
#define XK_PG_SYSDICT_DATERANGEARRAYOID 3913
#define XK_PG_SYSDICT_INT8RANGEOID 3926
#define XK_PG_SYSDICT_INT8RANGEARRAYOID 3927
#define XK_PG_SYSDICT_RECORDOID 2249
#define XK_PG_SYSDICT_RECORDARRAYOID 2287
#define XK_PG_SYSDICT_CSTRINGOID 2275
#define XK_PG_SYSDICT_ANYOID 2276
#define XK_PG_SYSDICT_ANYARRAYOID 2277
#define XK_PG_SYSDICT_VOIDOID 2278
#define XK_PG_SYSDICT_TRIGGEROID 2279
#define XK_PG_SYSDICT_EVTTRIGGEROID 3838
#define XK_PG_SYSDICT_LANGUAGE_HANDLEROID 2280
#define XK_PG_SYSDICT_INTERNALOID 2281
#define XK_PG_SYSDICT_OPAQUEOID 2282
#define XK_PG_SYSDICT_ANYELEMENTOID 2283
#define XK_PG_SYSDICT_ANYNONARRAYOID 2776
#define XK_PG_SYSDICT_ANYENUMOID 3500
#define XK_PG_SYSDICT_FDW_HANDLEROID 3115
#define XK_PG_SYSDICT_INDEX_AM_HANDLEROID 325
#define XK_PG_SYSDICT_TSM_HANDLEROID 3310
#define XK_PG_SYSDICT_ANYRANGEOID 3831

#elif XK_PG_VERSION_NUM >= 100000 && XK_PG_VERSION_NUM < 110000
/* OIDS 1 - 99 */
#define XK_PG_SYSDICT_BOOLOID            16
#define XK_PG_SYSDICT_BYTEAOID        17
#define XK_PG_SYSDICT_CHAROID            18
#define XK_PG_SYSDICT_NAMEOID            19
#define XK_PG_SYSDICT_INT8OID            20
#define XK_PG_SYSDICT_INT2OID            21
#define XK_PG_SYSDICT_INT2VECTOROID    22
#define XK_PG_SYSDICT_INT4OID            23
#define XK_PG_SYSDICT_REGPROCOID        24
#define XK_PG_SYSDICT_TEXTOID            25
#define XK_PG_SYSDICT_OIDOID            26
#define XK_PG_SYSDICT_TIDOID        27
#define XK_PG_SYSDICT_XIDOID 28
#define XK_PG_SYSDICT_CIDOID 29
#define XK_PG_SYSDICT_OIDVECTOROID    30

/* hand-built rowtype entries for bootstrapped catalogs */
/* NB: OIDs assigned here must match the BKI_ROWTYPE_OID declarations */
/* OIDS 100 - 199 */
#define XK_PG_SYSDICT_JSONOID 114
#define XK_PG_SYSDICT_XMLOID 142
#define XK_PG_SYSDICT_PGNODETREEOID    194
#define XK_PG_SYSDICT_PGNDISTINCTOID    3361
#define XK_PG_SYSDICT_PGDEPENDENCIESOID    3402
#define XK_PG_SYSDICT_PGDDLCOMMANDOID 32

/* OIDS 200 - 299 */

/* OIDS 300 - 399 */

/* OIDS 400 - 499 */

/* OIDS 500 - 599 */

/* OIDS 600 - 699 */
#define XK_PG_SYSDICT_POINTOID        600
#define XK_PG_SYSDICT_LSEGOID            601
#define XK_PG_SYSDICT_PATHOID            602
#define XK_PG_SYSDICT_BOXOID            603
#define XK_PG_SYSDICT_POLYGONOID        604
#define XK_PG_SYSDICT_LINEOID            628


/* OIDS 700 - 799 */
#define XK_PG_SYSDICT_FLOAT4OID 700
#define XK_PG_SYSDICT_FLOAT8OID 701
#define XK_PG_SYSDICT_ABSTIMEOID        702
#define XK_PG_SYSDICT_RELTIMEOID        703
#define XK_PG_SYSDICT_TINTERVALOID    704
#define XK_PG_SYSDICT_UNKNOWNOID        705
#define XK_PG_SYSDICT_CIRCLEOID        718
#define XK_PG_SYSDICT_CASHOID 790

/* OIDS 800 - 899 */
#define XK_PG_SYSDICT_MACADDROID 829
#define XK_PG_SYSDICT_INETOID 869
#define XK_PG_SYSDICT_CIDROID 650
#define XK_PG_SYSDICT_MACADDR8OID 774

/* OIDS 900 - 999 */

/* OIDS 1000 - 1099 */
#define XK_PG_SYSDICT_INT2ARRAYOID        1005
#define XK_PG_SYSDICT_INT4ARRAYOID        1007
#define XK_PG_SYSDICT_TEXTARRAYOID        1009
#define XK_PG_SYSDICT_OIDARRAYOID            1028
#define XK_PG_SYSDICT_FLOAT4ARRAYOID 1021
#define XK_PG_SYSDICT_ACLITEMOID        1033
#define XK_PG_SYSDICT_CSTRINGARRAYOID        1263
#define XK_PG_SYSDICT_BPCHAROID        1042
#define XK_PG_SYSDICT_VARCHAROID        1043
#define XK_PG_SYSDICT_DATEOID            1082
#define XK_PG_SYSDICT_TIMEOID            1083

/* OIDS 1100 - 1199 */
#define XK_PG_SYSDICT_TIMESTAMPOID    1114
#define XK_PG_SYSDICT_TIMESTAMPTZOID    1184
#define XK_PG_SYSDICT_INTERVALOID        1186

/* OIDS 1200 - 1299 */
#define XK_PG_SYSDICT_TIMETZOID        1266

/* OIDS 1500 - 1599 */
#define XK_PG_SYSDICT_BITOID     1560
#define XK_PG_SYSDICT_VARBITOID      1562

/* OIDS 1600 - 1699 */

/* OIDS 1700 - 1799 */
#define XK_PG_SYSDICT_NUMERICOID        1700
#define XK_PG_SYSDICT_REFCURSOROID    1790

/* OIDS 2200 - 2299 */
#define XK_PG_SYSDICT_REGPROCEDUREOID 2202
#define XK_PG_SYSDICT_REGOPEROID        2203
#define XK_PG_SYSDICT_REGOPERATOROID    2204
#define XK_PG_SYSDICT_REGCLASSOID        2205
#define XK_PG_SYSDICT_REGTYPEOID        2206
#define XK_PG_SYSDICT_REGROLEOID        4096
#define XK_PG_SYSDICT_REGNAMESPACEOID        4089
#define XK_PG_SYSDICT_REGTYPEARRAYOID 2211

/* uuid */
#define XK_PG_SYSDICT_UUIDOID 2950

/* pg_lsn */
#define XK_PG_SYSDICT_LSNOID            3220

/* xk_pg_parser_text search */
#define XK_PG_SYSDICT_TSVECTOROID        3614
#define XK_PG_SYSDICT_GTSVECTOROID    3642
#define XK_PG_SYSDICT_TSQUERYOID        3615
#define XK_PG_SYSDICT_REGCONFIGOID    3734
#define XK_PG_SYSDICT_REGDICTIONARYOID    3769

/* jsonb */
#define XK_PG_SYSDICT_JSONBOID 3802

/* range types */
#define XK_PG_SYSDICT_INT4RANGEOID        3904

/*
 * pseudo-types
 *
 * types with typtype='p' represent various special cases in the type system.
 *
 * These cannot be used to define table columns, but are valid as function
 * argument and result types (if supported by the function's implementation
 * language).
 *
 * Note: cstring is a borderline case; it is still considered a pseudo-type,
 * but there is now support for it in records and arrays.  Perhaps we should
 * just treat it as a regular base type?
 */
#define XK_PG_SYSDICT_RECORDOID        2249
#define XK_PG_SYSDICT_RECORDARRAYOID    2287
#define XK_PG_SYSDICT_CSTRINGOID        2275
#define XK_PG_SYSDICT_ANYOID            2276
#define XK_PG_SYSDICT_ANYARRAYOID        2277
#define XK_PG_SYSDICT_VOIDOID            2278
#define XK_PG_SYSDICT_TRIGGEROID        2279
#define XK_PG_SYSDICT_EVTTRIGGEROID        3838
#define XK_PG_SYSDICT_LANGUAGE_HANDLEROID        2280
#define XK_PG_SYSDICT_INTERNALOID        2281
#define XK_PG_SYSDICT_OPAQUEOID        2282
#define XK_PG_SYSDICT_ANYELEMENTOID    2283
#define XK_PG_SYSDICT_ANYNONARRAYOID    2776
#define XK_PG_SYSDICT_ANYENUMOID        3500
#define XK_PG_SYSDICT_FDW_HANDLEROID    3115
#define XK_PG_SYSDICT_INDEX_AM_HANDLEROID 325
#define XK_PG_SYSDICT_TSM_HANDLEROID    3310
#define XK_PG_SYSDICT_ANYRANGEOID        3831
#else
/* OIDS 1 - 99 */
#define XK_PG_SYSDICT_BOOLOID            16
#define XK_PG_SYSDICT_BYTEAOID        17
#define XK_PG_SYSDICT_CHAROID            18
#define XK_PG_SYSDICT_NAMEOID            19
#define XK_PG_SYSDICT_INT8OID            20
#define XK_PG_SYSDICT_INT2OID            21
#define XK_PG_SYSDICT_INT2VECTOROID    22
#define XK_PG_SYSDICT_INT4OID            23
#define XK_PG_SYSDICT_REGPROCOID        24
#define XK_PG_SYSDICT_TEXTOID            25
#define XK_PG_SYSDICT_OIDOID            26
#define XK_PG_SYSDICT_TIDOID        27
#define XK_PG_SYSDICT_XIDOID 28
#define XK_PG_SYSDICT_CIDOID 29
#define XK_PG_SYSDICT_OIDVECTOROID    30

/* hand-built rowtype entries for bootstrapped catalogs */
/* NB: OIDs assigned here must match the BKI_ROWTYPE_OID declarations */
/* OIDS 100 - 199 */
#define XK_PG_SYSDICT_JSONOID 114
#define XK_PG_SYSDICT_XMLOID 142
#define XK_PG_SYSDICT_PGNODETREEOID    194
#define XK_PG_SYSDICT_PGDDLCOMMANDOID 32

/* OIDS 200 - 299 */

/* OIDS 300 - 399 */

/* OIDS 400 - 499 */

/* OIDS 500 - 599 */

/* OIDS 600 - 699 */
#define XK_PG_SYSDICT_POINTOID        600
#define XK_PG_SYSDICT_LSEGOID            601
#define XK_PG_SYSDICT_PATHOID            602
#define XK_PG_SYSDICT_BOXOID            603
#define XK_PG_SYSDICT_POLYGONOID        604
#define XK_PG_SYSDICT_LINEOID            628

/* OIDS 700 - 799 */
#define XK_PG_SYSDICT_FLOAT4OID 700
#define XK_PG_SYSDICT_FLOAT8OID 701
#define XK_PG_SYSDICT_ABSTIMEOID        702
#define XK_PG_SYSDICT_RELTIMEOID        703
#define XK_PG_SYSDICT_TINTERVALOID    704
#define XK_PG_SYSDICT_UNKNOWNOID        705
#define XK_PG_SYSDICT_CIRCLEOID        718
#define XK_PG_SYSDICT_CASHOID 790

/* OIDS 800 - 899 */
#define XK_PG_SYSDICT_MACADDROID 829
#define XK_PG_SYSDICT_INETOID 869
#define XK_PG_SYSDICT_CIDROID 650

/* OIDS 900 - 999 */

/* OIDS 1000 - 1099 */
#define XK_PG_SYSDICT_INT2ARRAYOID        1005
#define XK_PG_SYSDICT_INT4ARRAYOID        1007
#define XK_PG_SYSDICT_TEXTARRAYOID        1009
#define XK_PG_SYSDICT_OIDARRAYOID            1028
#define XK_PG_SYSDICT_FLOAT4ARRAYOID 1021
#define XK_PG_SYSDICT_ACLITEMOID        1033
#define XK_PG_SYSDICT_CSTRINGARRAYOID        1263
#define XK_PG_SYSDICT_BPCHAROID        1042
#define XK_PG_SYSDICT_VARCHAROID        1043
#define XK_PG_SYSDICT_DATEOID            1082
#define XK_PG_SYSDICT_TIMEOID            1083

/* OIDS 1100 - 1199 */
#define XK_PG_SYSDICT_TIMESTAMPOID    1114
#define XK_PG_SYSDICT_TIMESTAMPTZOID    1184
#define XK_PG_SYSDICT_INTERVALOID        1186

/* OIDS 1200 - 1299 */
#define XK_PG_SYSDICT_TIMETZOID        1266

/* OIDS 1500 - 1599 */
#define XK_PG_SYSDICT_BITOID     1560
#define XK_PG_SYSDICT_VARBITOID      1562

/* OIDS 1600 - 1699 */

/* OIDS 1700 - 1799 */
#define XK_PG_SYSDICT_NUMERICOID        1700
#define XK_PG_SYSDICT_REFCURSOROID    1790

/* OIDS 2200 - 2299 */
#define XK_PG_SYSDICT_REGPROCEDUREOID 2202
#define XK_PG_SYSDICT_REGOPEROID        2203
#define XK_PG_SYSDICT_REGOPERATOROID    2204
#define XK_PG_SYSDICT_REGCLASSOID        2205
#define XK_PG_SYSDICT_REGTYPEOID        2206
#define XK_PG_SYSDICT_REGROLEOID        4096
#define XK_PG_SYSDICT_REGNAMESPACEOID        4089
#define XK_PG_SYSDICT_REGTYPEARRAYOID 2211

/* uuid */
#define XK_PG_SYSDICT_UUIDOID 2950

/* pg_lsn */
#define XK_PG_SYSDICT_LSNOID            3220

/* xk_pg_parser_text search */
#define XK_PG_SYSDICT_TSVECTOROID        3614
#define XK_PG_SYSDICT_GTSVECTOROID    3642
#define XK_PG_SYSDICT_TSQUERYOID        3615
#define XK_PG_SYSDICT_REGCONFIGOID    3734
#define XK_PG_SYSDICT_REGDICTIONARYOID    3769

/* jsonb */
#define XK_PG_SYSDICT_JSONBOID 3802

/* range types */
#define XK_PG_SYSDICT_INT4RANGEOID        3904

/*
 * pseudo-types
 *
 * types with typtype='p' represent various special cases in the type system.
 *
 * These cannot be used to define table columns, but are valid as function
 * argument and result types (if supported by the function's implementation
 * language).
 *
 * Note: cstring is a borderline case; it is still considered a pseudo-type,
 * but there is now support for it in records and arrays.  Perhaps we should
 * just treat it as a regular base type?
 */

#define XK_PG_SYSDICT_RECORDOID        2249
#define XK_PG_SYSDICT_RECORDARRAYOID    2287
#define XK_PG_SYSDICT_CSTRINGOID        2275
#define XK_PG_SYSDICT_ANYOID            2276
#define XK_PG_SYSDICT_ANYARRAYOID        2277
#define XK_PG_SYSDICT_VOIDOID            2278
#define XK_PG_SYSDICT_TRIGGEROID        2279
#define XK_PG_SYSDICT_EVTTRIGGEROID        3838
#define XK_PG_SYSDICT_LANGUAGE_HANDLEROID        2280
#define XK_PG_SYSDICT_INTERNALOID        2281
#define XK_PG_SYSDICT_OPAQUEOID        2282
#define XK_PG_SYSDICT_ANYELEMENTOID    2283
#define XK_PG_SYSDICT_ANYNONARRAYOID    2776
#define XK_PG_SYSDICT_ANYENUMOID        3500
#define XK_PG_SYSDICT_FDW_HANDLEROID    3115
#define XK_PG_SYSDICT_INDEX_AM_HANDLEROID 325
#define XK_PG_SYSDICT_TSM_HANDLEROID    3310
#define XK_PG_SYSDICT_ANYRANGEOID        3831
#endif

#endif
