#ifndef PG_PARSER_SYSDICT_PG_INDEX_H
#define PG_PARSER_SYSDICT_PG_INDEX_H

#define IndexRelationId 2610

typedef struct PG_PARSER_SYSDICT_PGINDEX
{
    uint32_t  indrelid;       /* OID of table */
    uint32_t  indexrelid;     /* OID of index */
    bool      indisprimary;   /* Whether index is generated by primary key */
    bool      indisreplident; /* Whether it is the index specified by replica identity */
    uint32_t  indnatts;       /* Number of index columns */
    uint32_t* indkey;         /* Index columns */
} pg_parser_sysdict_pgindex;

typedef pg_parser_sysdict_pgindex* pg_sysdict_Form_pg_index;

#endif
