#ifndef PG_PARSER_SYSDICT_PG_TYPE_H
#define PG_PARSER_SYSDICT_PG_TYPE_H

#define TypeRelationId 1247
#define TypeRelationIdChar "1247"
#define TypeRelation_Rowtype_Id 71

typedef struct PG_PARSER_SYSDICT_PGTYPE
{
    uint32_t                    oid;
    pg_parser_NameData       typname;
    int16_t                     typlen;
    bool                        typbyval;
    char                        typtype;
    char                        typdelim;
    uint32_t                    typelem;
    uint32_t                    typoutput;
    uint32_t                    typrelid;
    char                        typalign;
    char                        typstorage;
} pg_parser_sysdict_pgtype;

typedef pg_parser_sysdict_pgtype *pg_sysdict_Form_pg_type;

#define  PG_SYSDICT_TYPTYPE_BASE             'b' /* base type (ordinary scalar type) */
#define  PG_SYSDICT_TYPTYPE_COMPOSITE        'c' /* composite (e.g., table's rowtype) */
#define  PG_SYSDICT_TYPTYPE_DOMAIN           'd' /* domain over another type */
#define  PG_SYSDICT_TYPTYPE_ENUM             'e' /* enumerated type */
#define  PG_SYSDICT_TYPTYPE_PSEUDO           'p' /* pseudo-type */
#define  PG_SYSDICT_TYPTYPE_RANGE            'r' /* range type */
#define  PG_SYSDICT_TYPTYPE_NULL             'n' /* 指空类型, 自行添加, 非pg原生 */

#define  PG_SYSDICT_TYPCATEGORY_INVALID      '\0'    /* not an allowed category */
#define  PG_SYSDICT_TYPCATEGORY_ARRAY        'A'
#define  PG_SYSDICT_TYPCATEGORY_BOOLEAN      'B'
#define  PG_SYSDICT_TYPCATEGORY_COMPOSITE    'C'
#define  PG_SYSDICT_TYPCATEGORY_DATETIME     'D'
#define  PG_SYSDICT_TYPCATEGORY_ENUM         'E'
#define  PG_SYSDICT_TYPCATEGORY_GEOMETRIC    'G'
#define  PG_SYSDICT_TYPCATEGORY_NETWORK      'I' /* think INET */
#define  PG_SYSDICT_TYPCATEGORY_NUMERIC      'N'
#define  PG_SYSDICT_TYPCATEGORY_PSEUDOTYPE   'P'
#define  PG_SYSDICT_TYPCATEGORY_RANGE        'R'
#define  PG_SYSDICT_TYPCATEGORY_STRING       'S'
#define  PG_SYSDICT_TYPCATEGORY_TIMESPAN     'T'
#define  PG_SYSDICT_TYPCATEGORY_USER         'U'
#define  PG_SYSDICT_TYPCATEGORY_BITSTRING    'V' /* er ... "varbit"? */
#define  PG_SYSDICT_TYPCATEGORY_UNKNOWN      'X'

/* Is a type OID a polymorphic pseudotype?    (Beware of multiple evaluation) */
#define IsPolymorphicType(typid)  \
    ((typid) == PG_SYSDICT_ANYELEMENTOID || \
     (typid) == PG_SYSDICT_ANYARRAYOID || \
     (typid) == PG_SYSDICT_ANYNONARRAYOID || \
     (typid) == PG_SYSDICT_ANYENUMOID || \
     (typid) == PG_SYSDICT_ANYRANGEOID)

#define PG_SYSDICT_BOOLOID 16
#define PG_SYSDICT_BYTEAOID 17
#define PG_SYSDICT_CHAROID 18
#define PG_SYSDICT_NAMEOID 19
#define PG_SYSDICT_INT8OID 20
#define PG_SYSDICT_INT2OID 21
#define PG_SYSDICT_INT2VECTOROID 22
#define PG_SYSDICT_INT4OID 23
#define PG_SYSDICT_REGPROCOID 24
#define PG_SYSDICT_TEXTOID 25
#define PG_SYSDICT_OIDOID 26
#define PG_SYSDICT_TIDOID 27
#define PG_SYSDICT_XIDOID 28
#define PG_SYSDICT_CIDOID 29
#define PG_SYSDICT_OIDVECTOROID 30
#define PG_SYSDICT_JSONOID 114
#define PG_SYSDICT_XMLOID 142
#define PG_SYSDICT_PGNODETREEOID 194
#define PG_SYSDICT_PGNDISTINCTOID 3361
#define PG_SYSDICT_PGDEPENDENCIESOID 3402
#define PG_SYSDICT_PGMCVLISTOID 5017
#define PG_SYSDICT_PGDDLCOMMANDOID 32
#define PG_SYSDICT_POINTOID 600
#define PG_SYSDICT_LSEGOID 601
#define PG_SYSDICT_PATHOID 602
#define PG_SYSDICT_BOXOID 603
#define PG_SYSDICT_POLYGONOID 604
#define PG_SYSDICT_LINEOID 628
#define PG_SYSDICT_FLOAT4OID 700
#define PG_SYSDICT_FLOAT8OID 701
#define PG_SYSDICT_UNKNOWNOID 705
#define PG_SYSDICT_CIRCLEOID 718
#define PG_SYSDICT_CASHOID 790
#define PG_SYSDICT_MACADDROID 829
#define PG_SYSDICT_INETOID 869
#define PG_SYSDICT_CIDROID 650
#define PG_SYSDICT_MACADDR8OID 774
#define PG_SYSDICT_ACLITEMOID 1033
#define PG_SYSDICT_BPCHAROID 1042
#define PG_SYSDICT_VARCHAROID 1043
#define PG_SYSDICT_DATEOID 1082
#define PG_SYSDICT_TIMEOID 1083
#define PG_SYSDICT_TIMESTAMPOID 1114
#define PG_SYSDICT_TIMESTAMPTZOID 1184
#define PG_SYSDICT_INTERVALOID 1186
#define PG_SYSDICT_TIMETZOID 1266
#define PG_SYSDICT_BITOID 1560
#define PG_SYSDICT_VARBITOID 1562
#define PG_SYSDICT_NUMERICOID 1700
#define PG_SYSDICT_REFCURSOROID 1790
#define PG_SYSDICT_REGPROCEDUREOID 2202
#define PG_SYSDICT_REGOPEROID 2203
#define PG_SYSDICT_REGOPERATOROID 2204
#define PG_SYSDICT_REGCLASSOID 2205
#define PG_SYSDICT_REGTYPEOID 2206
#define PG_SYSDICT_REGROLEOID 4096
#define PG_SYSDICT_REGNAMESPACEOID 4089
#define PG_SYSDICT_UUIDOID 2950
#define PG_SYSDICT_LSNOID 3220
#define PG_SYSDICT_TSVECTOROID 3614
#define PG_SYSDICT_GTSVECTOROID 3642
#define PG_SYSDICT_TSQUERYOID 3615
#define PG_SYSDICT_REGCONFIGOID 3734
#define PG_SYSDICT_REGDICTIONARYOID 3769
#define PG_SYSDICT_JSONBOID 3802
#define PG_SYSDICT_JSONPATHOID 4072
#define PG_SYSDICT_TXID_SNAPSHOTOID 2970
#define PG_SYSDICT_INT4RANGEOID 3904
#define PG_SYSDICT_NUMRANGEOID 3906
#define PG_SYSDICT_TSRANGEOID 3908
#define PG_SYSDICT_TSTZRANGEOID 3910
#define PG_SYSDICT_DATERANGEOID 3912
#define PG_SYSDICT_INT8RANGEOID 3926
#define PG_SYSDICT_RECORDOID 2249
#define PG_SYSDICT_RECORDARRAYOID 2287
#define PG_SYSDICT_CSTRINGOID 2275
#define PG_SYSDICT_ANYOID 2276
#define PG_SYSDICT_ANYARRAYOID 2277
#define PG_SYSDICT_VOIDOID 2278
#define PG_SYSDICT_TRIGGEROID 2279
#define PG_SYSDICT_EVTTRIGGEROID 3838
#define PG_SYSDICT_LANGUAGE_HANDLEROID 2280
#define PG_SYSDICT_INTERNALOID 2281
#define PG_SYSDICT_OPAQUEOID 2282
#define PG_SYSDICT_ANYELEMENTOID 2283
#define PG_SYSDICT_ANYNONARRAYOID 2776
#define PG_SYSDICT_ANYENUMOID 3500
#define PG_SYSDICT_FDW_HANDLEROID 3115
#define PG_SYSDICT_INDEX_AM_HANDLEROID 325
#define PG_SYSDICT_TSM_HANDLEROID 3310
#define PG_SYSDICT_TABLE_AM_HANDLEROID 269
#define PG_SYSDICT_ANYRANGEOID 3831
#define PG_SYSDICT_BOOLARRAYOID 1000
#define PG_SYSDICT_BYTEAARRAYOID 1001
#define PG_SYSDICT_CHARARRAYOID 1002
#define PG_SYSDICT_NAMEARRAYOID 1003
#define PG_SYSDICT_INT8ARRAYOID 1016
#define PG_SYSDICT_INT2ARRAYOID 1005
#define PG_SYSDICT_INT2VECTORARRAYOID 1006
#define PG_SYSDICT_INT4ARRAYOID 1007
#define PG_SYSDICT_REGPROCARRAYOID 1008
#define PG_SYSDICT_TEXTARRAYOID 1009
#define PG_SYSDICT_OIDARRAYOID 1028
#define PG_SYSDICT_TIDARRAYOID 1010
#define PG_SYSDICT_XIDARRAYOID 1011
#define PG_SYSDICT_CIDARRAYOID 1012
#define PG_SYSDICT_OIDVECTORARRAYOID 1013
#define PG_SYSDICT_JSONARRAYOID 199
#define PG_SYSDICT_XMLARRAYOID 143
#define PG_SYSDICT_POINTARRAYOID 1017
#define PG_SYSDICT_LSEGARRAYOID 1018
#define PG_SYSDICT_PATHARRAYOID 1019
#define PG_SYSDICT_BOXARRAYOID 1020
#define PG_SYSDICT_POLYGONARRAYOID 1027
#define PG_SYSDICT_LINEARRAYOID 629
#define PG_SYSDICT_FLOAT4ARRAYOID 1021
#define PG_SYSDICT_FLOAT8ARRAYOID 1022
#define PG_SYSDICT_CIRCLEARRAYOID 719
#define PG_SYSDICT_MONEYARRAYOID 791
#define PG_SYSDICT_MACADDRARRAYOID 1040
#define PG_SYSDICT_INETARRAYOID 1041
#define PG_SYSDICT_CIDRARRAYOID 651
#define PG_SYSDICT_MACADDR8ARRAYOID 775
#define PG_SYSDICT_ACLITEMARRAYOID 1034
#define PG_SYSDICT_BPCHARARRAYOID 1014
#define PG_SYSDICT_VARCHARARRAYOID 1015
#define PG_SYSDICT_DATEARRAYOID 1182
#define PG_SYSDICT_TIMEARRAYOID 1183
#define PG_SYSDICT_TIMESTAMPARRAYOID 1115
#define PG_SYSDICT_TIMESTAMPTZARRAYOID 1185
#define PG_SYSDICT_INTERVALARRAYOID 1187
#define PG_SYSDICT_TIMETZARRAYOID 1270
#define PG_SYSDICT_BITARRAYOID 1561
#define PG_SYSDICT_VARBITARRAYOID 1563
#define PG_SYSDICT_NUMERICARRAYOID 1231
#define PG_SYSDICT_REFCURSORARRAYOID 2201
#define PG_SYSDICT_REGPROCEDUREARRAYOID 2207
#define PG_SYSDICT_REGOPERARRAYOID 2208
#define PG_SYSDICT_REGOPERATORARRAYOID 2209
#define PG_SYSDICT_REGCLASSARRAYOID 2210
#define PG_SYSDICT_REGTYPEARRAYOID 2211
#define PG_SYSDICT_REGROLEARRAYOID 4097
#define PG_SYSDICT_REGNAMESPACEARRAYOID 4090
#define PG_SYSDICT_UUIDARRAYOID 2951
#define PG_SYSDICT_PG_LSNARRAYOID 3221
#define PG_SYSDICT_TSVECTORARRAYOID 3643
#define PG_SYSDICT_GTSVECTORARRAYOID 3644
#define PG_SYSDICT_TSQUERYARRAYOID 3645
#define PG_SYSDICT_REGCONFIGARRAYOID 3735
#define PG_SYSDICT_REGDICTIONARYARRAYOID 3770
#define PG_SYSDICT_JSONBARRAYOID 3807
#define PG_SYSDICT_JSONPATHARRAYOID 4073
#define PG_SYSDICT_TXID_SNAPSHOTARRAYOID 2949
#define PG_SYSDICT_INT4RANGEARRAYOID 3905
#define PG_SYSDICT_NUMRANGEARRAYOID 3907
#define PG_SYSDICT_TSRANGEARRAYOID 3909
#define PG_SYSDICT_TSTZRANGEARRAYOID 3911
#define PG_SYSDICT_DATERANGEARRAYOID 3913
#define PG_SYSDICT_INT8RANGEARRAYOID 3927
#define PG_SYSDICT_CSTRINGARRAYOID 1263

#endif
