#ifndef _TRANSLOG_RECVLOGDB_H_
#define _TRANSLOG_RECVLOGDB_H_

typedef enum TRANSLOG_RECVLOG_DBVERSION
{
    TRANSLOG_RECVLOG_VERSION_NOP             = 0x00,
    TRANSLOG_RECVLOG_PGVERSION_1             ,
    TRANSLOG_RECVLOG_PGVERSION_2             ,
    TRANSLOG_RECVLOG_PGVERSION_3             ,
    TRANSLOG_RECVLOG_PGVERSION_4             ,
    TRANSLOG_RECVLOG_PGVERSION_5             ,
    TRANSLOG_RECVLOG_PGVERSION_6             ,
    TRANSLOG_RECVLOG_PGVERSION_7             ,
    TRANSLOG_RECVLOG_PGVERSION_8             ,
    TRANSLOG_RECVLOG_PGVERSION_9             ,
    TRANSLOG_RECVLOG_PGVERSION_10            ,
    TRANSLOG_RECVLOG_PGVERSION_11            ,
    TRANSLOG_RECVLOG_PGVERSION_12            ,
    TRANSLOG_RECVLOG_PGVERSION_13            ,
    TRANSLOG_RECVLOG_PGVERSION_14            ,
    TRANSLOG_RECVLOG_PGVERSION_15            ,
    TRANSLOG_RECVLOG_PGVERSION_16            ,
    TRANSLOG_RECVLOG_PGVERSION_17            ,
    TRANSLOG_RECVLOG_PGVERSION_18            ,

    /* PG 版本在此前添加 */
    TRANSLOG_RECVLOG_PGVERSION_MAX
} translog_recvlog_dbversion;


typedef enum TRANSLOG_RECVLOG_DBTYPE
{
    TRANSLOG_RECVLOG_DBTYPE_NOP              = 0x00,
    TRANSLOG_RECVLOG_DBTYPE_PG,
    TRANSLOG_RECVLOG_DBTYPE_MAX
} translog_recvlog_dbtype;

#endif
